nebari-dev/nebari

- docs/index.md
- qhub/template/hooks/prompt_gen_project.py
Adds hyperlinks to the Quansight logo and the word `Quansight` in the opening paragraph for the documentation. Hyperlink routes to the main Quansight web page.
> Add hyperlink for quansight logo and name

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/gcp.tf
Since we recently added support for preemptible on terraform modules wanted to add the preemptible option to qhub
> Adding preemptible option to nodegroups for gcp

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
Causes downstream errors with generated terraform files. Need to add to qhub github-actions to do a formatting check #107 which will be in new PR
> Fix terraform formatting issue with aws kubernetes.tf generation

- docs/docs/do/installation.md
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/image.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/do.tf
Due recent support added in qhub-terraform-modules https://github.com/Quansight/qhub-terraform-modules/pull/22
This is still a WIP need to find out how to automate https://www.digitalocean.com/docs/images/container-registry/quickstart/#use-images-in-your-registry-with-kubernetes
> Enable DigitalOcean to use private container registry

- docs/_templates/layout.html
- docs/conf.py
This PR adds a _templates folder with the ability to override the sphinx-material theme colors.
cc @dharhas @tonyfast
> override colors

- docs/docs/step-by-step-walkthrough.md
Here are some proposed changes. Foremost I thought the "scripts" reference was not necessary since config and deployment is handled nicely with "qhub render" and "qhub deploy". Tried to also make it more generic for other DNS services and be a little more prescriptive of how to use AWS vs DO/GCP. And since it's October, and the PR is accepted, I guess there is the Hacktoberfest merit possible...
> Jkellndorfer patch step by step guide 1

- qhub/deploy.py
Replace `AWS_ACCESS_SECRET_ACCESS_KEY` with `AWS_SECRET_ACCESS_KEY`.
> Fix bug: wrong spelling of an AWS env variable

- qhub/deploy.py
Sometimes parsing the terraform output fails for no reason, this basically adds some logging around it and also spits the command output for debugging.
> Add logging around output parsing failure

- qhub/initialize.py
The GitHub client secret wasn't saved because of a bug: probably a copy and paste error.
> Fix bug in `initialize.py`

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
Fixes #261 
See this: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide#changes-to-kubernetes-credentials-supplied-in-the-provider-block
> Remove the unsupported argument for k8s provider

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/do.tf
Since this is unused. I have not removed the GCP/AWS ones at the moment, since they are not causing any problems (happy to remove them as well, if people think so).
The problem is following by the way:
I realised that one can create only one registry per DigitalOcean account:
Now when I try to create a registry, I get:
Error: Error creating container registry: POST https://api.digitalocean.com/v2/registry: 422 user already has a registry
Which makes sense, but when I enter the name of the repository for creation, instead of returning the already existing repository, it gives me the following error:
Error: Error creating container registry: POST https://api.digitalocean.com/v2/registry: 409 name already exists
Terraform docs: https://registry.terraform.io/providers/digitalocean/digitalocean …
> Remove registry for DigitalOcean

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/variables.tf
Fixes #286 
The jinja boolean check syntax was wrong. This fixes it.
> Fix prefect cookiecutter check

- docs/source/02_get_started/04_configuration.md
- docs/source/06_developers_contrib_guide/04_local_development.md
- qhub/initialize.py
To follow the standard default username we currently use in onprem, the original `costrouc` was modified to `example-user` as well as it's correlated mentions in the docs. The default password fingerprint in the [docs](https://github.com/Quansight/qhub-cloud/blob/dev/docs/source/06_developers_contrib_guide/04_local_development.md#initialize-kubernetes-cluster) was also modified to match the default username.
#349
> Remove `costrouc` as the default user in qhub

- qhub/cli/deploy.py
- qhub/initialize.py
- setup.py
During qhub init if auth type is password, generates a random password and prints:
`Your QHub password for example-user is {example_password}`
Closes #414
> Generate a random password for example-user

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/jupyterhub.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/templates/jupyterhub_config.py.j2
These were the forgotten lines
https://github.com/Quansight/qhub-cloud/blob/7f7e8b43a3be46a40bae01c03d76bb3145119540/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/jupyterhub.yaml#L143-L151
Closes https://github.com/Quansight/qhub-cloud/issues/370
Closes https://github.com/Quansight/qhub-cloud/issues/393
> FIXUP: Forgot part of jupyterhub_config when moving towards templates

- .github/workflows/test.yaml
- README.md
- RELEASE.md
- docs/source/02_get_started/03_usage.md
- docs/source/02_get_started/04_configuration.md
- docs/source/03_tutorials_and_samples/1_project_setup_tutorial.md
- docs/source/06_developers_contrib_guide/04_tests.md
- qhub/cli/deploy.py
- qhub/cli/render.py
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/qhub-ops.yaml
There are two main motivations for the move:
- simplify the instructions for getting started with qhub
- often times users forget to render before a deploy when modifying the `qhub-config.yaml`
Closes https://github.com/Quansight/qhub-cloud/issues/413
> Render by default in the deploy command of qhub

- docs/source/02_get_started/04_configuration.md
- docs/source/04_how_to_guides/1_qhub-aws-deploy_guide.md
- docs/source/04_how_to_guides/2_qhub-gcp-deploy_guide.md
- docs/source/04_how_to_guides/3_qhub-do-deploy_guide.md
- qhub/initialize.py
- qhub/schema.py
- qhub/template/cookiecutter.json
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/image-pr.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/image.yaml
This feature was run into with the recent change of github to use `main` as the default branch. Additionally I'd really like to simplify our IIAC github-actions code to make it easier to port to other ci providers (e.g. gitlab)
> Adding field to configure the branch being used for CI/CD

- .github/workflows/test.yaml
- qhub/initialize.py
- qhub/schema.py
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/aws.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/variables.tf
AWS_DEFAULT_REGION was always set as a GitHub secret when `qhub init` auto-provisions a GitHub repo, but the region was never set in the qhub-config.yaml file. It was always left as a hardcoded us-west-2.
Additionally, availability_zones of us-west-2a and us-west-2b were hardcoded.
This PR:
-  respects AWS_DEFAULT_REGION and inserts that into qhub-config.yaml
- no longer requires availability_zones to be set in qhub-config.yaml
- if qhub-config.yaml does contain availability_zones those will be used
Note that availability_zones is still allowed in qhub-config.yaml:
1. for backwards-compatibility
2. in case the user does have a preference
However, I do not believe it is possible to use `qhub deploy` to migrate an existing qhub to newly-specified availability zones (or regions, for that …
> AWS_DEFAULT_REGION respected, and availibility zones not needed

- qhub/cli/__init__.py
- qhub/cli/initialize.py
- qhub/initialize.py
- qhub/provider/terraform.py
- qhub/utils.py
Previously, terraform errors were silent and did not propagate into qhub cli.
Now they are raised (for init, apply, destroy) and qhub returns exit code 1, so GitHub actions know it failed.
Also return exit code 1 for other validation errors etc, and check project/namespace regex in a better place to allow for manually input values where not passed on the command line.
> Terraform errors are caught, and qhub returns exit code 1

- qhub/template/{{ cookiecutter.repo_directory }}/templates/jupyterhub_config.py.j2
This PR adds a setting to jupyterhub_config which ensures the dashboard owner has to pick a server profile when they first launch a dashboard.
The downside is that if they stop their server, only they can restart it.
The upside is that they:
1. Can choose which profile they want...
2. Showing the form sets the initContainers correctly so permissions are set
> spawn_default_options False to force dashboard owner to pick profile

- qhub/cli/deploy.py
- qhub/deploy.py
- qhub/template/{{ cookiecutter.repo_directory }}/.gitlab-ci.yml
When doing infrastructure as code update via github-actions and gitlab-ci the remote state has already been provisioned. We need a way within CI to tell `qhub deploy` to not actually run the `terraform apply` within the `terraform-state` directory since the remote state is already created.
> Adding command line argument to skip provisioning remote-state on deployment

- qhub/template/{{ cookiecutter.repo_directory }}/templates/jupyterhub_config.py.j2
Sets c.CDSDashboardsConfig.conda_envs in jupyterhub_config so that the user can choose the Conda Env when creating/editing the dashboard.
Closes #530
> Set conda_envs for dashboards

- qhub/cli/destroy.py
- qhub/deploy.py
- qhub/destroy.py
- qhub/provider/terraform.py
- qhub/state.py
- qhub/utils.py
To improve `qhub destroy`:
- Render terraform files before destroy (like deploy) by default
- Assume terraform-state/terraform.tfstate is old or not present (for remote backends)
- Import state from cloud
This is especially useful for integration tests because the state buckets are not currently being destroyed, making it difficult to start the test next time round.
AWS/GCP now working. Attempt at Digital Ocean import but fails with:
```
[terraform]: module.terraform-state.module.spaces.digitalocean_spaces_bucket.main: Importing from ID "qhubintgrtndo-dev-terraform-state"...
[terraform]: module.terraform-state.module.spaces.digitalocean_spaces_bucket.main: Import prepared!
[terraform]:   Prepared digitalocean_spaces_bucket for import
[terraform]: …
```
> Improvements to qhub destroy and terraform-state sync

- qhub/deploy.py
- qhub/destroy.py
- qhub/initialize.py
- qhub/schema.py
- qhub/utils.py
Removed defaults from pydantic schema since they were causing missing values to remain missing, and the defaults were never used anyway - so confusing for developers to see them there. Defaults aren't used because Pydantic is being used for validation but not model initialization.
Closes #539 
GitHub auto-provision - returns errors if provision fails or secrets missing, warns if repo already exists.
Closes #557
> Pydantic correct validation, github auto-provision checks

- docs/source/02_get_started/02_setup.md
- docs/source/02_get_started/04_configuration.md
- docs/source/03_tutorials_and_samples/1_project_setup_tutorial.md
- docs/source/04_how_to_guides/2_qhub-gcp-deploy_guide.md
- qhub/initialize.py
- qhub/schema.py
- qhub/template/cookiecutter.json
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/image.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/gcp.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/gcp/kubernetes/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/variables.tf
- qhub/template/{{ cookiecutter.repo_directory }}/terraform-state/main.tf
- qhub/utils.py
AWS_DEFAULT_REGION no longer needed.
For GCP, `zone` is removed from qhub-config.yaml, and availability_zones is optional - pulls default from Google if not specified.
To avoid clusters being torn down inadvertently, once set availability_zones cannot be changed (this was the same for the similar PR I did for AWS).
> Cloud Regions simplified

- qhub/cli/validate.py
- qhub/provider/cicd/linter.py
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/qhub-linter.yaml
This approach aims to execute a specific file for linting called `linter.py`. Right now it only utilizes `qhub validate` (`verify(config)`), but we are able to put even more linting abilities to it in the future, without changing all the process.
close #379
> Qhub linter

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/locals.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/forwardauth/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/forwardauth/variables.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/dask-gateway/middleware.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/meta/qhub/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/meta/qhub/variables.tf
- qhub/template/{{ cookiecutter.repo_directory }}/templates/jupyterhub_config.py.j2
Uses forwardauth to protect dask dashboards behind JupyterHub auth using a new oauth client.
Note any JupyterHub user can access any dashboard.
> Secure dask dashboard behind forwardauth

- docs/source/03_tutorials_and_samples/03_dask_gateway_usage.md
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/dask_gateway_config.py.j2
Fixes #599 
Here is a working deployed example:
https://nbviewer.jupyter.org/gist/aktech/4ec2b8cd275a0e3205e0bb76365a7d3c
> Add ability to set environment vars to Dask workers

- docs/source/04_how_to_guides/7_qhub_gpu.md
- qhub/schema.py
- qhub/template/cookiecutter.json
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/aws.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/aws/kubernetes/locals.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/aws/kubernetes/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/aws/kubernetes/nvidia-device-plugin.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/aws/kubernetes/variables.tf
> Add support for GPUs on AWS

- qhub/initialize.py
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterhub/environment.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/environment.yaml
Traitlets >= 5.0 seems to have a backwards-incompatibility that affected the VariableSpawner used in cdsdashboards.
This works around it.
Closes #602
> Traitlets fix

- qhub/cli/__init__.py
- qhub/cli/validate.py
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/qhub-linter.yaml
This provides a little more context for the user upon failure during schema
validation of the qhub config yaml (example is
https://github.com/Quansight/qhub/issues/593). I found this error message
a little too impenetrable... lack of experience no doubt but this might be
helpful to the next poor unfortunate.
> make message for schema validation failure more informative

- qhub/destroy.py
- qhub/provider/terraform.py
The terraform destroy fails on AWS if there is a significant delay between apply and destroy. This is why it was not caught in the integration tests.
The primary reason for this is in terraform >= 0.14, terraform doesn't refreshes the terraform state before generating a plan to destroy resources. This PR runs the refresh before destroy in order to cleanly destroy everything.
> Terraform refresh before destroy to avoid failing destroy

- qhub/template/{{ cookiecutter.repo_directory }}/templates/jupyterhub_config.py.j2
kubespawner_override.environment merges with spawner.environment to preserve dashboard vars JUPYTERHUB_ANYONE and JUPYTERHUB_GROUP.
Remove typing from kubespawner_override to achieve this.
The problem was that these env vars are needed to control access to dashboards, but were being overwritten by kubespawner_overrides, in v0.3.11.
Closes #624 
I'm not sure when this bug was introduced, but could be related to traitlets>=5.0 and/or kubespawner>=1.0
The current main branch pins dependencies more explicitly and this should help.
> kubespawner_override.environment merges with spawner.environment

- docs/source/03_tutorials_and_samples/1_project_setup_tutorial.md
The DNS name was previously required to be prepended with `jupyter.<domain>`. This is no longer a requirement, and running `qhub init --domain <domain_name>` will deploy qhub to <domain_name>
> Update 1_project_setup_tutorial.md to remove reference to jupyter.<domain>

- docs/source/02_get_started/03_usage.md
- docs/source/03_tutorials_and_samples/1_project_setup_tutorial.md
- qhub/cli/initialize.py
- qhub/initialize.py
- qhub/schema.py
Can explicitly provide --ci-provider=none to qhub init (don't have to completely omit the parameter).
This makes integration tests easier.
> Allow explicit ci-provider=none

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/dask-gateway/controler.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/dask-gateway/middleware.tf
Closes #636 
There was a problem in upgrading a qhub that had the old definition of qhub-dask-gateway-cluster because Terraform wasn't updating the type to a 'chain' middleware.
> Rename qhub-dask-gateway-cluster to -chain

- qhub/schema.py
This should fix schema validation error for `prefect: true` new field in the `qhub-config.yml` file.
This seems to be the current error message when attempt to deploy QHub with prefect in it:
```bash
Problem encountered: 1 validation error for Main
prefect
extra fields not permitted (type=value_error.extra)
```
See [discussion](https://github.com/Quansight/qhub/pull/641#issuecomment-859101173) 
Closes #114
> ADD prefect optional field

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/aws/network/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/aws/network/variables.tf
Changes the network mask for the QHub subnets on AWS from `x.x.x.x/24` to `x.x.x.x/20` to increase the number of available IP addresses
> Change subned cidr mask

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/cluster-autoscaler/main.tf
`helm_repository` data source is deprecated now.
> Fix helm upgrade: remove helm_repository data source

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/cluster-autoscaler/main.tf
Ref: https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#argument-reference
This is weird, it should worked without it ideally.
> Remove repo name from chart name: helm_release

- qhub/schema.py
- qhub/utils.py
fix #209 
This PR adds new validators under Pydantic `schema.py`: 
- `check_default` to guarantee that only one instance under Jupyterlab has defined as `default: true`;
- `validate_userids` to guarantee that there is no repeated user id under the users profiles.
The `yaml.safe_load` function inside `qhub render` and [`qhub deploy`](https://github.com/Quansight/qhub/blob/426d327246a5e40a21d8244e2728c917b20386d8/qhub/cli/deploy.py#L55) currently checks the last problem commented in that issue 
> multiple environments with the same name
> Additional config validation checks

- qhub/render/__init__.py
This PR builds the name for the conda-store PVC using the `namespace` variable from the config, in the case that the user has changed it from the default value of "dev".
Should resolve #708.
Apologies I don't have any idea how to test this, but submitting in case it's useful.
> Include namespace in conda-store PVC

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/forwardauth/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/ingress/variables.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/clearml/ingress.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/clearml/variables.tf
> Secure ClearML behind forwardauth

- .github/workflows/test.yaml
- docs/source/02_get_started/04_configuration.md
- qhub/deploy.py
- qhub/render/__init__.py
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/prefect/variables.tf
- tests/test_deploy.py
- tests/test_render.py
Resolves #13.
Proposal for managing secrets... this approach:
+ Makes use of the fact that terraform variables can be set by setting an environment variable with the same name but prefixed with `TF_VAR_`
+ Could be used for all secrets/tokens.
+ Makes it harder for secrets to leak as they are never stored as plain text.
+ Does not expose secrets during a render (I need to confirm this, I may have to define the variable as sensitive in variables.tf).
+ Can serve as an interim prior to more thorough managment of secrets using something like vault/keycloak.
+ In some cases will require the removal of some values from the schema. e.g. client_id and client_key for google oauth.
> remove secrets from config yaml and terraform configuration files

- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/environment.yaml
In our QHub deployment we've found it useful to add a couple of jupyterlab extensions. The first is the `jupyter-resource-usage` extension which shows memory used/available on the VM running lab. The second is the `nbgitpuller` package which allows distributing URLs that load a given notebook into the JupyterHub service. Thought I'd suggest these as generally good additions to include in the lab image.
> Add lab extensions jupyter-resource-usage and nbgitpuller

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/aws/kubernetes/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/nfs-mount/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/conda-store/main.tf
Fixes #738 #735 
At the moment, I have increased the default size of node in AWS to 50GB, in future we might want to parameterise it.
> Fix conda-store pod eviction and volume conflicts

- qhub/initialize.py
I found my general node (s-2vcpu-4gb) ran out of RAM on Digital Ocean, so replacing with the cheapest 8GB droplet type here.
> Digital Ocean default general node now s-4vcpu-8gb

- docs/source/dev_guide/testing.md
This fixes a dead hyperlink that points to the old dev branch
> Fix Broken Hyperlink in Docs

- docs/source/admin_guide/troubleshooting.md
- qhub/schema.py
- qhub/template/cookiecutter.json
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/extcr/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/extcr/variables.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/meta/qhub/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/meta/qhub/variables.tf
Allow user to specify a private external AWS ECR as a replacement for Docker Hub for selected images, on any cloud.
Add to qhub-config.yaml:
```
external_container_reg:
enabled: true
access_key_id: <AWS access key id>
secret_access_key: <AWS secret key>
extcr_account: 892486800165
extcr_region: eu-west-2
```
If this section is completely omitted, qhub should never complain (and assume enabled=false).
> External Container Registry

- docs/source/dev_guide/testing.md
Following the Firefox workaround for Traefik's self-signed certificate, a working Chrome browser workaround, given its preloaded HSTS domain list. It's not terribly elegant but it works.
> Chrome self-signed cert workaround

- docs/source/admin_guide/clearml.md
- qhub/schema.py
- qhub/template/cookiecutter.json
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/clearml/ingress.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/clearml/variables.tf
This makes ForwardAuth optional for ClearML.
> Make ForwardAuth optional for ClearML

- tests_e2e/cypress/notebooks/BasicTest.ipynb
What will be nice here is running a python script when the dask gateway is up and running a couple of tests to check that Dask Gateway is reachable.
> Spin up dask-gateway via Cypress

- qhub/render/__init__.py
- tests/test_render.py
Closes #767 
The approach taken will only remove files/directories found in the `deletable_dirs` list. In the linked issue, the acceptance criteria specifies removing all `os.remove` and `shutil.rmtree` logic so my current solution employs `Path` object methods (which essentially do the same thing). 
I have also added a `verbosity` flag (currently set to `0` - none) if and when we would like to output the list of files/directories being deleted. 
All feedback is welcome :)
> Update `remove_existing_renders` to only delete qhub related files/directories

- qhub/schema.py
There are four different types of Authentication object that can appear in the qhub-config.yaml, all with slightly different formats.
The previous schema code allowed all variations through - but failed to stop Pydantic allowing some invalid forms through.
Below are three examples of YAML that might be expected.
For GitHub:
```
security:
authentication:
type: GitHub
config:
client_id: githubclient
client_secret: githubsecret
oauth_callback_url: https://qhubtest.com/hub/oauth_callback
```
For plain passwords - note there is no `config` section at all:
```
security:
authentication:
type: password
```
For custom authenticators - note there is an extra `authentication_class` field required, and `config` has extra fields compared to that for GitHub above (in fact, for custom we allow any …
> Pydantic validation for auth

- .github/ISSUE_TEMPLATE/bug-report---.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request---.md
- README.md
This PR adds some improvements to the issue templates and the Readme and therefore the user experience and introduction to the project:
- :wrench: Add issue template config
- :memo: Update bug template
- :memo: Update feature template
- :memo: Better readme
> Improvements to templates and readme

- .cirun.yml
- .github/workflows/kubernetes_test.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
This skips the failure on the cleanup step to remove noise from the CI.
- Updated the AMI with cypress dependencies to reduce time in installation: `ami-0ff297f01f579288c`
> Fix CI: skip failure on cleanup

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/versions.tf
- pins terraform cloud providers 
I would say best way to test is with the auto deploy tests of qhub.
> Pin terraform providers

- .github/workflows/kubernetes_test.yaml
- .github/workflows/test.yaml
- docs/source/dev_guide/testing.md
- environment-dev.yaml
- setup.py
- tests_deployment/constants.py
- tests_deployment/test_dask_gateway.py
- tests_deployment/utils.py
Sets up a simple framework for writing integration/deployment tests for the deployed QHub on minikube.
Currently added basic tests for Dask Gateway.
Added tests for running via pytest.
> Setup/Add integration/deployment tests via pytest

- docs/source/admin_guide/index.md
- docs/source/admin_guide/jupyterhub.md
- docs/source/admin_guide/keycloak.md
- docs/source/admin_guide/prefect.md
- docs/source/admin_guide/system_maintenance.md
- docs/source/admin_guide/troubleshooting.md
- docs/source/admin_guide/upgrade.md
- docs/source/dev_guide/minikube.md
- docs/source/dev_guide/testing.md
- docs/source/installation/configuration.md
- docs/source/installation/login.md
- docs/source/installation/management.md
- docs/source/installation/usage.md
- docs/source/user_guide/dashboard.md
- docs/source/user_guide/getting_started.md
- docs/source/user_guide/ssh.md
- qhub/schema.py
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterhub/environment.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/environment.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/jupyterhub/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/jupyterhub/values.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/meta/qhub/main.tf
- tests/vale/styles/Google/Exclamation.yml
- tests/vale/styles/Google/Latin.yml
- tests/vale/styles/Google/Quotes.yml
- tests/vale/styles/vocab.txt
> Allow jupyterhub.overrides in qhub-config.yaml

- qhub/cli/destroy.py
- qhub/destroy.py
- qhub/provider/terraform.py
There are many reasons why `qhub destroy` fails, including timeouts in terraform which are hard to set globally.
Sometimes the Kubernetes cluster starts to be destroyed before Terraform has formally had a chance to destroy some of the software deployed within Kubernetes, resulting in the error that the cluster is not accessible to destroy that software.
Since the Keycloak provider needs to make API calls to Keycloak within the cluster, terraform command can fail terminally if the provider is configured with a Keycloak URL that no longer exists.
A more robust definition system as proposed in [Split infrastructure into components](#847) might help since it would allow destroy to be done in stages, so we can be sure one stage is complete before we advance to the next.
Maybe a move to …
> qhub destroy using targets

- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/qhub-ops.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
In AWS integration tests, sometimes we see namespace is trying to be created before cluster is fully up.
Terraform should maybe spot this dependency anyway since provider needs to use outputs but maybe this will help.
- kubernetes-initialization depends_on kubernetes
> kubernetes-initialization depends_on kubernetes

- qhub/provider/terraform.py
Fixes #933
Adds a timeout to the subprocess for `terraform import` of 30 seconds. Without this timeout deploying on GCP will hang and give the error that that the bucket doesn't exist
> Add timeout to terraform import command

- qhub/provider/terraform.py
- qhub/utils.py
Fixes #933
- timeout is now handled within Python subprocess
Maybe the previous attempt to fix this didn't work on Mac... now trying this fix on Linux!
> Timeout in process (for import)

- qhub/render/__init__.py
- qhub/schema.py
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/keycloak-config/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/keycloak-config/variables.tf
Fixes #920 
- No longer allows `security.users` and `security.groups` in `qhub-config.yaml`
This means that all user management must now be in Keycloak.
> Remove user/groups from YAML

- qhub/cli/upgrade.py
- qhub/upgrade.py
- tests/qhub-config-yaml-files-for-upgrade/qhub-config-do-310-customauth.yaml
- tests/qhub-config-yaml-files-for-upgrade/qhub-config-do-310.yaml
- tests/qhub-config-yaml-files-for-upgrade/qhub-users-import.json
- tests/scripts/minikube-loadbalancer-ip.py
- tests/test_schema.py
- tests/test_upgrade.py
Fixes #931 - qhub upgrade should reject custom authenticators [bug]
- Running `qhub upgrade` will throw an error advising that custom authenticators are no longer supported.
- Users will be told they can run `qhub upgrade --attempt-fixes` instead. This will change the `qhub-config.yaml` to the basic Keycloak password authentication.
- Pytests added for upgrade command, including 'normal yaml from v3.10' and custom authenticator (resulting in error, or being fixed by --attempt-fixes)
I decided not to pollute documentation with a description of the --attempt-fixes flag since that is self-documenting - it reveals itself if it is needed, and will ideally give the user a chance to understand and think about …
> qhub upgrade custom auth plus tests

- .github/workflows/image.yaml
- docs/source/user_guide/experimental.md
- qhub/template/{{ cookiecutter.repo_directory }}/image/Dockerfile.dask-worker-centos
- qhub/template/{{ cookiecutter.repo_directory }}/image/Dockerfile.jupyterlab-centos
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/yum.txt
- qhub/template/{{ cookiecutter.repo_directory }}/image/scripts/install-yum-minimal.sh
- qhub/template/{{ cookiecutter.repo_directory }}/image/scripts/install-yum.sh
Fixes | Closes | Resolves #884 
- Add two new images, increase the number of images qhub maintains to seven.
- `qhub-jupyterlab-centos`
- `qhub-dask-worker-centos` 
- Update `image.yaml` to ensure these two new images also get built.
This PR does not change any of the `ubuntu` images or how they are built and this PR is takes another chunk out of the large PR #904. 
I have added docs to illustrate how to swap out `ubuntu`-based images with `centos`-based images. 
There is more work that can be done to simplify the …
> Add minimal support `centos` images

- docs/source/admin_guide/backup.md
- qhub/keycloak.py
- scripts/keycloak-export.py
Fixes #919
- Added a scripts/keycloak-export.py script to export users/groups from Keycloak
- Documentation added to 'Manual Backups'
- Also talk about JupyterHub DB backup in the docs
> Keycloak Export

- .pre-commit-config.yaml
- docs/source/admin_guide/jupyterhub.md
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterhub/environment.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/jupyterhub.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/meta/qhub/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/meta/qhub/variables.tf
- qhub/template/{{ cookiecutter.repo_directory }}/templates/jupyterhub_config.py.j2
Merge hub.extraEnv env vars and hub.extraConfig in jupyterhub helm chart.
If the following is in the qhub-config.yaml file:
```
jupyterhub:
overrides:
hub:
config:
Authenticator:
enable_auth_state: true
extraEnv:
- name: "MYENV1"
value: "11111"
- name: "MYENV2"
value: "22222"
extraConfig:
new-config-thing: |
c.KubeSpawner.something = 123
```
then, despite the overrides supposed to be added to the JupyterHub Helm release, previously anything under `hub.extraEnv` would be lost when further overridden by QHub's own required env vars.
This PR merges them instead so the user's env vars should make it into the Hub pod.
Similarly for extraConfig.
> Merge hub.extraEnv env vars

- docs/source/admin_guide/keycloak.md
- qhub/schema.py
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/keycloak-config/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/keycloak-config/variables.tf
- Adds an optional `security.keycloak.realm_display_name` setting to override the `qhub` realm display name, e.g. on the Keycloak login page.
> keycloak.realm_display_name

- .github/workflows/docs.yml
- .github/workflows/image.yaml
- .github/workflows/kubernetes_test.yaml
- .github/workflows/test-provider.yaml
- .github/workflows/test.yaml
- README.md
- docs/index.md
- setup.py
This PR:
- Removes support for Python 3.6
- Adds support for Python 3.9
- Add concurrency variable to cancel old builds
- Fix broken links on `README.md`
> CI changes for QHub

- qhub/upgrade.py
- qhub/version.py
Fixes | Closes | Resolves #991 
Manually tested functionality.
> Remove `scope`, `oauth_callback_url` during upgrade step

- .pre-commit-config.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/ingress/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/conda-store/config/conda_store_config.py
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/conda-store/server.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/conda-store/storage.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/minio/ingress.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/minio/variables.tf
Fixes #980 
- Add additional port to handle Minio object storage
Testing locally and on GCP.
> FEAT: Add additional port to handle Minio object storage

- .github/workflows/image.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/postBuild
Fixes #1000 
On December 16th [code-server repo updated their `install.sh` file](https://github.com/coder/code-server/blob/ec3d9974b3494e6055c8e65e1fb0e4bc665429a7/install.sh), and updated their download URLs, causing the `postbuild` phase for the Jupyterlab image to fail. This PR updates the download URL for their installer.
Also, on January 18th our docker build/push action got [a new release](https://github.com/docker/build-push-action/releases/tag/v2.8.0) including support for [Handlebars](https://handlebarsjs.com/guide/), which conflicted with our main path for template images: `./qhub/templates/{{ cookiecutter.repo_directory }}`, as they seem to have added some kind of parser for the handlers that broke our workflow.
- Updates the snapshot URL for [code-server bash installer …
> Fix Jupyterlab docker build

- .github/workflows/test.yaml
- qhub/deploy.py
- qhub/keycloak.py
- setup.cfg
Fixes #1018
- black some missing files and format using flake8
- add an exception for traitlets config over testing actions
> Fix formatting issues with black #1003

- qhub/deploy.py
Fixes #1022
Increasing the number of attempts and timeout for checking if the keycloak server is in a running state might solve the flacky tests.
- Increase number of attempts and timeout condition for requesting access to keycloak admin URI
> Increase timeout/attempts for keycloak check

- docs/source/admin_guide/index.md
- docs/source/admin_guide/traefik.md
- qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/main.tf
- qhub/template/stages/05-kubernetes-keycloak/modules/kubernetes/keycloak-helm/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/forwardauth/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/clearml/ingress.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/server.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/dask-gateway/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/minio/ingress.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/monitoring/main.tf
- tests/vale/styles/vocab.txt
The core of the issue was that for entrypoints a default certResolver
was not being specified. Additionally had to read some docs within
traefik https://doc.traefik.io/traefik/routing/entrypoints/#tls that
state that is a `tls = {}` section is specified within the crd
ingressroute the tls configuration is overwritten.
```
If a TLS section (i.e. any of its fields) is user-defined, then the
default configuration does not apply at all.
```
Fixes #1015 
- changes related to traefik ingress
Tested locally using minikube and using digitalocean
> Fix issue with traefik issueing certificates with letsencrypt acme

- qhub/template/stages/07-kubernetes-services/jupyterhub.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/02-spawner.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/variables.tf
This is a short term fix for conda-store environments being shown in
cdsdashboards. Longer term we will need to consult the conda-store
rest api or filesystem for available environments (for 0.4.x release).
Fixes #1019
- added environments from `qhub-config.yaml` to cdsdashboards list.
> Fixing cdsdashboard conda environments being shown

- qhub/template/stages/06-kubernetes-keycloak-configuration/variables.tf
Fixes #1028 
The current `map` type for `authentication` lead to terraform to decide the type of variables it will be receiving from the input. But, when using extra forms of authentication like `Github, Auth0` the extra field `authentication.config` has a dict type structure, and `authentication.type` has an str type structure which lead to the following error when deploying the stage:
```
... map elements must have the same type.
```
edit.: Opted for variable type: `any` as using `object` structure obliges the variable input to have the same structure as specified which conflicts with the authentication modes of qhub (some does not include the `config` key)
- Update variable `authentication` type to include multiple value types.
_Put an …
> Fix input variable support for multiple types

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- pyproject.toml
Attempt to solve black problems seen on GitHub Actions but not CI.
We used to exclude cookie-cutter template folder from black, but this has obviously been replaced by template/stages which has a few random python files (e.g. jupyterhub_config.py).
These weren't safe to run through black before because they were jinja2 templates. It would be safe now, but I don't think it really makes sense to run black/flake8 on the template folder, so will submit a PR shortly.
- Exclude `qhub/template` from flake8 and black in both pre-commit and pyproject.toml
> Fix Black/Flake8 problems [WIP]

- qhub/template/image/jupyterlab/environment.yaml
- qhub/template/image/jupyterlab/postBuild
- added code-server >= 3.2 in the JupyterLab environment.yml file
- replaced the previous JupyterLab extension with the one of betatim
- cleaned-up code required for the previous way of installing code server
Closes #903
> Code Server is now installed via conda, and the Jupyterlab Extension is https://github.com/betatim/vscode-binder/

- flake.nix
- setup.cfg
Simple PR that removes cookiecutter from setup.cfg requirements. Also update flake.nix to allow for qhub to still build.
> Removing cookiecutter from setup.cfg requirements

- qhub/deploy.py
- qhub/template/stages/06-kubernetes-keycloak-configuration/main.tf
- qhub/template/stages/06-kubernetes-keycloak-configuration/variables.tf
There was a bug in that we no longer suported the `security.keycloak.realm_display_name` .This is now supported.
> Fixup adding support for security.keycloak.realm_display_name key

- docs/source/dev_guide/minikube.md
- docs/source/installation/configuration.md
- docs/source/installation/existing.md
- docs/source/installation/management.md
- qhub/deploy.py
- qhub/schema.py
- qhub/template/stages/06-kubernetes-keycloak-configuration/main.tf
- qhub/template/stages/06-kubernetes-keycloak-configuration/variables.tf
- qhub/upgrade.py
Closes #957
This adds an option for `security.shared_users_group` which is by
default False. If True all users created after this option is set True
will be added to the `users` group. If any users were created before
this option they must manually be added to this group.
> Adding security.shared_users_group option for default users group

- docs/source/installation/configuration.md
- qhub/deploy.py
- qhub/template/stages/07-kubernetes-services/jupyterhub.tf
Prior to #1003 there was the option `jupyterhub.overrides`. Here we
are adding back this option and ensuring that there is documentation
on the option.
> Fixup adding back jupyterhub overrides option

- docs/source/admin_guide/upgrade.md
- qhub/cli/deploy.py
- qhub/deploy.py
- qhub/schema.py
- qhub/upgrade.py
- tests/test_schema.py
Also fix --skip-remote-state-provision and remove --full-only which is no longer used)
Fixes #1040 
Added a `prevent_default` field to the `qhub-config.yaml` that will be set after `qhub upgrade` to 0.4.0. This stops users blindly redeploying without understanding the full upgrade process.
Also
- Fixed `--skip-remote-state-provision` which was being ignored
- Removed `--full-only` flag which was no longer used
I have added general upgrade documentation but we also need to spell out the full upgrade process in release notes and/or docs.
> prevent_deploy flag for safeguarding upgrades

- .github/workflows/image.yaml
This PR:
- Adds layer caching for Docker images
- Adds an `if:` statement where a log-in step would be run only on pushes and workflow runs
|Image       |CI time (before)     |CI time (after)      |
|------------|---------------------|---------------------|
|Jupyterlab  |~10 minutes          |~30 seconds          |
|Jupyterhub  |~2 minutes 41 seconds|~2 minutes 14 seconds|
|Dask-worker |~3 minutes           |~2 minutes 27 seconds|
|Dask-gateway|~40 seconds          |~36 seconds          |
- [CI before](https://github.com/Quansight/qhub/runs/5174291033?check_suite_focus=true)
- [CI after](https://github.com/Quansight/qhub/runs/5174357150?check_suite_focus=true)
> CI: Add layer caching for Docker images

- .github/workflows/docs.yml
- .github/workflows/image.yaml
- .github/workflows/kubernetes_test.yaml
- .github/workflows/test-provider.yaml
- .github/workflows/test.yaml
- qhub/template/image/docker-bake.json
- tests/scripts/minikube-loadbalancer-ip.py
- tests_e2e/cypress/integration/main.js
Closes #1084 
This PR has a few goals:
- Make it so that only the tests that need to run actually run for CI given commits
- build the docker images for each kubernetes test
> More finely scoped github actions and kubernetes_test build docker images

- qhub/deploy.py
- qhub/destroy.py
- qhub/render.py
- qhub/stages/checks.py
- qhub/stages/input_vars.py
- qhub/stages/state_imports.py
- qhub/stages/tf_objects.py
- qhub/utils.py
This PR is only a refactor of render, deploy, and destroy. The motivation for this is allowing for the closing of #1081. In order to properly delete the aws ingress we need to be able to get the terraform outputs from some early kubernetes stages. This PR will also allow for the easier transition to #865.
There are no modifications to the behavior of the code.
Going into more detail about the heart of the issue:
For each stage we have to supply input variables, dymanic terraform objects, terraform imports. 
We cannot run `terraform output` without supplying the proper input variables. Within deploy.py and destroy.py this was becoming repetative. Thus I've moved the definitions into a `stages/*.py` directory which will need to be done with whatever extension mechanism we chose.
> Reorganizing render, deploy, destroy to unify stages input_vars, tf_objects, checks, and state_imports

- qhub/provider/cicd/github.py
- qhub/provider/cicd/gitlab.py
- qhub/render/__init__.py
- qhub/utils.py
- Additions and fixes related to #1068 
> Updates/fixes for rendering CICD workflows

- qhub/stages/input_vars.py
- qhub/stages/state_imports.py
- qhub/stages/tf_objects.py
- qhub/template/stages/01-terraform-state/azure/main.tf
- qhub/template/stages/01-terraform-state/azure/modules/terraform-state/main.tf
- qhub/template/stages/01-terraform-state/azure/modules/terraform-state/variables.tf
Fixes | Closes | Resolves #1082 
This PR should fix the above-linked issue by creating specific groups, containers, and storage resources for terraform-state files.
- Update resource group name, for terraform state stage
- Update backend configuration following the same changes
- Add a new variable to deploy for the custom resource group name (in theory)
> Generate independet objects for terraform-state resources

- qhub/deploy.py
- qhub/destroy.py
- qhub/render.py
- qhub/stages/checks.py
- qhub/utils.py
Closes #1092
This is a tricky implementation since we have multiple stages. Several of these stages require credentials kubernetes and keycloak to work. Destroy now works like the following
```
stages: 01, 02, 03, ... 08
for stage in stages:
stage_ouputs = terraform output (stage)
for stage in reversed(stages):
terraform destroy 
```
kubernetes and keycloak context are applied correctly along with all needed variables
> Complete implementation of destroy which goes through each stage

- qhub/provider/terraform.py
- qhub/stages/tf_objects.py
- qhub/template/stages/03-kubernetes-initialize/providers.tf
- qhub/template/stages/04-kubernetes-ingress/providers.tf
- qhub/template/stages/05-kubernetes-keycloak/providers.tf
- qhub/template/stages/07-kubernetes-services/providers.tf
- qhub/template/stages/08-qhub-tf-extensions/providers.tf
Fixes | Closes | Resolves #1106 
- this PR changes the aws credentials from being stored and used by each stage to instead being fetched each time the kubernetes provider is used (using data). 
This follows best practices outlined in https://github.com/hashicorp/terraform-provider-kubernetes/tree/main/_examples/eks. Later we may want to adopt this for other clouds.
These changes should not add or remove any features.
> Change AWS Kubenetes provider authentication to use data.eks_cluster instead of exec

- qhub/deploy.py
- qhub/initialize.py
- qhub/schema.py
Simplifies the default template generated by `qhub init` so that the jupyterlab and dask worker images in `default_images` are actually what is deployed. Previous to this PR there are images that override the default images in the template for `qhub-config.yaml`
> Simplify default images

- qhub/stages/input_vars.py
- qhub/template/stages/06-kubernetes-keycloak-configuration/main.tf
- qhub/template/stages/06-kubernetes-keycloak-configuration/variables.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/config/conda_store_config.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/server.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/dask-gateway/files/gateway_config.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/03-profiles.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/monitoring/main.tf
- qhub/upgrade.py
Fixes #1075 
Fixes #1085 
@costrouc Please check I haven't confused conda-store or grafana roles...
- remove `viewer` group
- rename `practitioner` to `analyst`
- make `analyst` a default group for new users
- stop the `/projects` structure, so every group now corresponds to a shared folder
> Change group structure

- qhub/keycloak.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/variables.tf
- tests_e2e/cypress/integration/main.js
This adds routes to visit the keycloak user account page, conda-store, and grafana monitoring just to check that pages are up
Closes #1121
> Adding tests to visit additional endpoints

- .github/workflows/kubernetes_test.yaml
- flake.nix
- setup.cfg
- tests_deployment/assets/notebook/simple.ipynb
- tests_deployment/constants.py
- tests_deployment/test_jupyterhub_ssh.py
- tests_e2e/cypress/integration/main.js
- tests_e2e/cypress/support/index.js
From my testing jupyterhub-ssh does not fully work as an expected ssh session. Currently it is hanging at times with 
```
/opt/conda/condabin/conda
/opt/conda/condabin/conda
```
And then hanging and not giving a shell.
> Adding tests for juypterhub-ssh, jhub-client, and vs code 

- docs/source/installation/login.md
- docs/source/user_guide/troubleshooting.md
- qhub/stages/checks.py
- tests/vale/styles/vocab.txt
Fixes | Closes | Resolves #1036 
References #1032, #1076, #1009
- Add troubleshooting doc which outlines two common issues we've experienced when testing v0.4.0 release.
- "DNS domain=`your_qhub_domain` record does not exist"
- A Conda-Store environment fails to build
If this is a relatively large or complex change, kick off the …
> [DOC] Add `troubleshooting` docs

- qhub/stages/checks.py
Fixes | Closes | Resolves #1147 
- Use `list_namespace()` instead of `list_node()` as a means of checking the kubernetes cluster created in stage 02 is up and running.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered and …
> Workaround for kubernetes-client version issue

- qhub/initialize.py
- qhub/provider/cicd/github.py
- qhub/provider/cicd/gitlab.py
- qhub/schema.py
Fixes | Closes | Resolves 
Replaces PR #995 
- Make the commit of the terraform rendering optional in the `qhub_ops.yaml` / `.gitlab_ci.yaml`
> Make the commit of the terraform rendering optional (replaces PR 995)

- .mdformat.toml
- .pre-commit-config.yaml
Closes #1113  
- Add [`mdformat`](https://github.com/executablebooks/mdformat) to wrap doc lines, explicitly added the configuration toml to further change in the default settings. 
- Set wrap line length to 180.
Any wrapping will automatically happen when a `.md` file is committed.
> Add markdown formatter for doc wrapping

- .cirun.yml
This param is not required anymore. Cirun will automatically provision required number of runners.
-
> remove deprecated param `count` from `.cirun.yml`

- docs/source/installation/login.md
- qhub/deploy.py
- qhub/schema.py
- qhub/stages/input_vars.py
- qhub/template/stages/05-kubernetes-keycloak/modules/kubernetes/keycloak-helm/outputs.tf
- qhub/template/stages/05-kubernetes-keycloak/outputs.tf
Fixes | Closes | Resolves #1165 
- Use `qhub_bot` keycloak user to perform keycloak validations during the deployment. As opposed to relying on the `root` keycloak user.   
Thanks @danlester walking me through how to resolve this bug!!
If this is a relatively large or complex change, kick off the discussion by explaining why you …
> Use qhub-bot for keycloak deployment/check

- RELEASE.md
- Add release notes for the v0.4.0 release
> DOCS: Add release notes for v0.4.0 release

- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/config/conda_store_config.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/server.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/worker.tf
Fixes two issues:
- ipykernel can be missing when a new environment is created
- conda-store services on redeployment do not load new config without annotation trick
> Adding ipykernel as default to environment along with ensure conda-store restarted on config change

- qhub/stages/input_vars.py
- qhub/template/stages/07-kubernetes-services/conda-store.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/storage.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/variables.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/minio/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/minio/variables.tf
> Setting minio storage to by default be same as filesystem size for Conda-Store environments

- qhub/template/stages/06-kubernetes-keycloak-configuration/main.tf
- qhub/template/stages/06-kubernetes-keycloak-configuration/social_auth.tf
- qhub/template/stages/06-kubernetes-keycloak-configuration/versions.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/keycloak-client/versions.tf
- qhub/template/stages/07-kubernetes-services/versions.tf
- qhub/template/stages/08-qhub-tf-extensions/modules/qhubextension/main.tf
- qhub/template/stages/08-qhub-tf-extensions/versions.tf
I repeatedly saw problems when trying to deploy locally with minikube.
The qhub keycloak realm seemed to fail to be created, causing the subsequent keycloak config to fail ("Realm not found")
This PR seems to make things better, although I'm not sure of the root cause. I also think related Terraform problems can still occur later on in non-keycloak components, but we will have to keep an eye on that separately.
minikube v1.25.2 on Ubuntu 20.04 (amd64)
Using the docker driver
Kubernetes v1.23.3 on Docker 20.10.12 ...
All in a Parallels VM on Mac
- Upgrade mrparkers/keycloak to 3.7.0
- Set some defaults in keycloak_realm
> Upgrade mrparkers to 3.7.0

- docs/source/admin_guide/system_maintenance.md
- docs/source/installation/configuration.md
- qhub/schema.py
- qhub/template/stages/06-kubernetes-keycloak-configuration/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/keycloak-client/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/keycloak-client/variables.tf
- qhub/upgrade.py
- tests/test_upgrade.py
Fixes #1191 
`profiles.jupyterlab` in `qhub-config.yaml` now has an `access` field - can be `all`, `keycloak`, `yaml`
- If `yaml`, also specify `groups` and/or `users` fields to restrict access to those users
- If `all` everyone will have access
- If `keycloak` access is granted to users/groups with the Keycloak attribute `jupyterlabprofiles` containing the `display_name` in their lists
Added `qhub upgrade` mechanism for this.
Group attributes are no longer overwritten on non-initial deploys (previously the pre-existing groups would have attributes reset).
> Profilegroups

- .github/workflows/test-provider.yaml
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/02-spawner.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/03-profiles.py
Fixes | Closes | Resolves #1202
- Merge spawner and profile env vars to ensure dashboard sharing vars are provided to dashboard servers
> Merge spawner and profile env vars

- docs/source/installation/configuration.md
- qhub/schema.py
- qhub/stages/input_vars.py
- qhub/template/stages/04-kubernetes-ingress/main.tf
- qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/main.tf
- qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/variables.tf
- qhub/template/stages/04-kubernetes-ingress/variables.tf
Fixes | Closes | Resolves #1210 
- Adds support for terraform overrides in ingress's load balancer.
> Support for pinning the IP address of the load balancer via terraform overrides

- docs/source/installation/configuration.md
- qhub/schema.py
- qhub/stages/input_vars.py
- qhub/template/stages/02-infrastructure/azure/modules/kubernetes/main.tf
- qhub/template/stages/02-infrastructure/azure/modules/kubernetes/variables.tf
Add support for terraform overrides in cloud and VPC deployment for Azure
Resolves partially #1211 for Azure
- Add ability to override terraform for Azure to be able to provide `vnet_subnet_id` and `private_cluster_enabled`
Manually deployed on Azure
If this is a relatively large or complex change, kick off the discussion by …
> Add support for terraform overrides in cloud and VPC deployment for Azure

- qhub/stages/tf_objects.py
Fixes | Closes | Resolves #1228 #1254
- Add AWS provider configuration to terraform state files where Kubernetes provider was initialized;
- This adds the missing region variable, explained in #1254 
This is a simple change to be added and does not require further testing as I was able to successfully deploy Qhub on AWS without the env variable workaround after this. The strange part is that we didn't see this error during 0.4.0/0.4.1 pre-release testing.
> Fix missing region from AWS provider

- docs/source/installation/configuration.md
- qhub/stages/input_vars.py
- qhub/template/image/jupyterhub/environment.yaml
Fixes | Closes | Resolves #1274 
- Add a condition to set theme version programmatically when `display_version` is True;
- bump `qhub-jupyterhub-theme==0.3.5` to fix the conflicting behavior for the dashboards page and version display;
- Fix some doc typos
> Fix display version behavior

- docs/source/admin_guide/prefect.md
- qhub/provider/cicd/github.py
Fixes | Closes | Resolves #878 
- Add a secret key to CI/CD config on GH, for when Prefect token is required
- Changed Prefect token env var syntax from `TF_VAR_prefect_token` to `QHUB_SECRET_PREFECT_TOKEN`
The reason why I changed the syntax lies in the fact we now support the direct inclusion of variables to terraform which was not feasible by Terraform infrastructure only in 0.3.+. Also, by using the `QHUB_SECRET` prefix, we are indeed using the [omitting sensitive values](https://docs.qhub.dev/en/stable/source/installation/configuration.html?#omitting-sensitive-values) settings from this type of information.
If so have you updated the …
> Add prefect token var to CI when needed

- qhub/template/image/jupyterlab/environment.yaml
this pull request adds `retrolab` to the base jupyter environment. `notebook>=7` will deploy a classic version of the notebook that is based on `jupyterlab` components. til then `retrolab` needs to be explicitly installed. likely, we'll remove this change in the future. in the meantime, it allows us to understand the feel or `retrolab` in common workflows.
> add `retrolab` to the base jupyter image

- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/minio/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/postgresql/main.tf
Fixes | Closes | Resolves - Related to #1306 
-
> Update minio, postgresql chart repo location

- qhub/stages/input_vars.py
- qhub/template/stages/03-kubernetes-initialize/modules/cluster-autoscaler/main.tf
- qhub/template/stages/03-kubernetes-initialize/modules/extcr/main.tf
Fixes | Closes | Resolves # 1302
- enables scaling to zero
- updates autoscaler helm chart to an actively updated chart (https://github.com/kubernetes/autoscaler)
@costrouc @viniciusdc I think this justifies a minor release prior to the Nebari rename. Scaling to 0 is a major improvement, and this currently fixes a bug which prevents successful AWS deployment.
> Fix broken AWS, set minimum desired size to 1, enable 0 scaling

- RELEASE.md
- qhub/stages/input_vars.py
- qhub/template/stages/03-kubernetes-initialize/modules/cluster-autoscaler/main.tf
- qhub/template/stages/03-kubernetes-initialize/modules/extcr/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/minio/main.tf
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/postgresql/main.tf
> v0.4.2 release notes

- qhub/template/image/jupyterlab/environment.yaml
Fixes | Closes | Resolves #1012 
-
This updated jupyterlab image has already been added to `beta` deployment if anyone wants to test it out. We needed this for the …
> install dask lab ext from main

- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterlab/overrides.json
Fixes | Closes | Resolves #1326 
- Updates the default value of `browserDashboardCheck` from `False` to `True`
This will guarantee that every spawned profile has the fix for the dask-gateway and dask-labextension dashboard issue.
This is a very simple addition to address the remaining needs of #1012
> Overrides default value for dask-labextension

- docs/source/installation/configuration.md
- docs/source/installation/existing.md
- qhub/initialize.py
Closes #1111 and https://github.com/nebari-dev/nebari/issues/37
- Doubled the profile sizes for the small and medium workers.
- Doubled the node sizes across the board for all cloud providers
- Increased the default conda-store storage to 200G, and the shared filesystem to 200G as well
- Updated documentation to reflect these changes
After talking to several people on the nebari team and checking some existing deployment profiles, I've doubled the node and profile sizes across the board. If others feel that we should increase these defaults further, I'm happy to make that change.
> Increase the default instance sizes

- .github/ISSUE_TEMPLATE/release-checklist.md
- .github/ISSUE_TEMPLATE/testing-checklist.md
- docs/source/dev_guide/release.md
Related to https://github.com/nebari-dev/governance/issues/2
- Enables maintainers to easily create a release checklist that can guide them through the release process.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered and …
> Add release-checklist issue template

- qhub/template/image/Dockerfile.dask-worker
- qhub/template/image/dask-worker/environment.yaml
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/dask-gateway/variables.tf
- qhub/utils.py
Closes #1296 
- Bumped `qhub-dask` to version `0.4.3`, which includes `distributed==2022.04.2` and `dask-gateway==2022.4.0`
Github workflows for testing new versions of qhub-dask before they get released to conda-forge will be addressing in #1339. Until then, testing was carried out on an existing qhub deployment, see the discussion at https://github.com/conda-forge/qhub-dask-feedstock/pull/14 for more information.
> Bump qhub-dask version to 0.4.3

- qhub/deploy.py
- qhub/initialize.py
- qhub/utils.py
> Revert "Remove the need for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to be set with Digital Ocean deployment"

- docs/source/installation/configuration.md
- docs/source/user_guide/environments.md
Closes #1345.
Both the dask-worker environment and the default dask client environment don't have a pinned python version, it's only dictated by the current requirements of `qhub-dask`. So the only updates necessary are documentation changes.
> Drop support for python 3.7 in dask environment

- qhub/cli/cost.py
- qhub/cost.py
Fixes #1351
- Provide an option (`--dashboard` or `-d`) to user to check if they need a shareable link of the dashboard. Defaults to `True` in case not provided.
- Provide an option (`--file` or `-f`) to user to download infracost reports locally.
- Provide an option (`--currency` or `-c`) to user to customize the infracost report currency with preferred [ISO 4217 currency](https://en.wikipedia.org/wiki/ISO_4217#Active_codes)
- Provide an option (`--compare` or `-ct`) to user to compare deployment costs across different deployments and present them a new table with the breakdown along with a shareable link of the dashboard
> Improvements in the QHub Cost estimate tool

- .github/ISSUE_TEMPLATE/testing-checklist.md
- Add a new item to the testing checklist to validate if the current version of qhub loads the previous YAML config and if the required `upgrade` config was added.
This might require an extra issue for further discussion as to how we should keep track of the necessary changes required to include in the `upgrade` command.
> Add backwards compatibility item to test checklist

- qhub/template/image/scripts/install-code-server.sh
https://github.com/Quansight/qhub/issues/1380
> add code server version to fix build

- qhub/initialize.py
Related to https://github.com/Quansight/qhub/issues/1359
- Add two new packages to Dask env, `pyarrow` and `s3fs`
> [ENH] Add `pyarrow` and `s3fs`

- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/config/conda_store_config.py
> Fixing bug in authentication method in Conda-Store authentication

- qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/main.tf
- qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/variables.tf
- qhub/template/stages/04-kubernetes-ingress/variables.tf
related to #1418 
- FIxed incorrect assignment of load balancer annotations, from `kubernetes_service.spec.selector` to `kubernetes_service.metadata` according to [documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#attaching-metadata-to-objects) and vide [example](https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer) 
- Updated variable `type`, from `map(object({...}))` to `map(string)`, as `object` [restricts the variable structure to match object specification. ](https://www.terraform.io/language/expressions/type-constraints#object)
If so have you updated the …
> Update Ingress overrides behaviour

- qhub/schema.py
- qhub/stages/input_vars.py
- qhub/template/stages/04-kubernetes-ingress/main.tf
- qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/main.tf
- qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/variables.tf
- qhub/template/stages/04-kubernetes-ingress/variables.tf
Fixes | Closes | Resolves #1418 
- This change will allow qhub users to disable TLS certificates altogether. This might be needed for those with unique deployment requirements. 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …
> Add option to disable tls certificate

- qhub/cli/_init.py
- qhub/cli/main.py
> Nebari cli: Add files _init.py and main.py

- flake.nix
- qhub/deploy.py
- qhub/destroy.py
- qhub/render.py
This fixes and issue when using provider=existing in 0.4.4rc4. This is broken before the release. 
Can reproduce when using `qhub init existing ...`.
> Fixing provider=existing for local/existing

- qhub/cli/deploy.py
- qhub/deploy.py
-Under special circumstances, users might need to disable the checks that take place at the end of each stage. This new flags allows for that possibility.  
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …
> Add `--disable-checks` flag to deploy

- qhub/template/stages/04-kubernetes-ingress/main.tf
- qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/main.tf
- qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/variables.tf
- qhub/template/stages/04-kubernetes-ingress/variables.tf
ingress.terraform_overrides.additional-arguments: [...]
See https://doc.traefik.io/traefik/reference/static-configuration/cli/
> Adding option to supply additional arguments to ingress via `ingress.terraform_overrides.additional-arguments`

- qhub/cli/main.py
- setup.cfg
> Nebari typer cli commands

- qhub/template/stages/03-kubernetes-initialize/modules/traefik_crds/main.tf
- Add the ability to add `headers` to traefik middleware 
> Add properties to middleware crd headers

- qhub/cli/main.py
> Nebari deploy and destroy commands

- qhub/initialize.py
- Pin `ipywidgets` to `7.7.1` for the Dask built-in environment.
The latest `ipywidgets` `8.x` removed an essential method used by `dask-gateway` when using the client widgets. This is a short-term solution.
> Pin dask ipywidgets version to `7.7.1`

- qhub/stages/input_vars.py
Fixes | Closes | Resolves #1490 
- There were two lines missing that are needed to pass AWS region and kubernetes version to the Terraform scripts. 
> Pass AWS `region`, `kubernetes_version` to terraform scripts

- qhub/template/stages/02-infrastructure/aws/main.tf
- qhub/template/stages/02-infrastructure/aws/modules/kubernetes/locals.tf
- qhub/template/stages/02-infrastructure/aws/modules/kubernetes/main.tf
- qhub/template/stages/02-infrastructure/aws/modules/kubernetes/variables.tf
- qhub/template/stages/02-infrastructure/aws/variables.tf
~Fixes | Closes | Resolves #~ Related to: #1488
- Add required `aws-ebs-csi-driver` on AWS for kubernetes v1.23+
- https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
- 1.23 is now the latest Kubernetes version
- Corollary to  #1493 
- ensure that `region` and `kubernetes_version` are passed to tf scripts 
> Enable ebs-csi driver on AWS, add region + kubernetes_version vars

- nebari/cli/main.py
- Update  `skip_remote_state_provision` default value from `True` to `False`
By keeping the `skip_remote_state_provision` default value as `True,` we were inadvertently revoking the creation of the terraform state bucket during the first deployments. Which is used during the stage provision phase:
https://github.com/nebari-dev/nebari/blob/77d15e7a16e87bfef234bdf4802bf622f6030618/nebari/deploy.py#L201-L208
I think the reason we didn't spot this sooner as due to until #1519 we still used a mix …
> Update `skip_remote_state_provision` default value

- README.md
- RELEASE.md
- Update RELEASE.md and add a warning to the README.md
> Add release notes for 2022.10.1

- .github/ISSUE_TEMPLATE/release-checklist.md
- .github/workflows/release.yaml
- If a leading `v` is added to the release tag (such as `v2022.10.1`), the release actual will remove it. This ensures that the release action runs successfully. 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives …
> Remove leading `v` for release action

- .cirun.yml
- .github/workflows/kubernetes_test.yaml
Sometimes it happens, when a runner is created for a job, it gets consumed by a job queued earlier, causing confusion sometimes. This PR makes sure, the runner is only consumed by the job it was created by. It's cirun's new feature, read more here: https://docs.cirun.io/reference/unique-runner-labels
> CI: Spinup unique cirun runners for each job

- .cirun.yml
- .github/workflows/contributor.yaml
- .github/workflows/infracost.yml
- .github/workflows/kubernetes_test.yaml
- .github/workflows/test-provider.yaml
With this members can trigger CI on contributor's PR with the following comment on the PR:
```
/bot run tests
```
TODO (right before merging the PR):
> Facilitate CI run for contributor PR

- nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/argo-workflows/main.tf
> Ensure Argo-Workflow controller containerRuntimeExecutor is set to emissary

- scripts/aws-force-destroy.sh
Script to forcefully delete AWS cluster using the `aws` cli:
https://github.com/nebari-dev/nebari/discussions/1590
> Create aws-force-destroy bash script

- .pre-commit-config.yaml
- nebari/template/stages/02-infrastructure/gcp/modules/kubernetes/main.tf
I created a new Nebari cluster to test that this would work as expected. I also upgraded an existing cluster to validate that it would work for those clusters as well. No issues detected. Node pools may be destroyed and recreated if there are version differences. More information about `release_channel` can be found [here](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels) and [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#release_channel).
> Set GKE release_channel to unspecified to prevent auto k8s updates

- nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_notebook_config.py
This PR raises the timeout length for a jupyter session.  I believe it changed it the right place.  Please let me know if there is another place.
fixes  #1615
https://github.com/nebari-dev/nebari/issues/1615
- [x ] Other (please describe):
> PR: Raise timeout for jupyter session

- nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
This PR will reduce the time it takes for a dashboard launch to timeout.  It is now set to 5 minutes. There was some discussion about making this configurable, but I thought that could go in another PR, and at least lower it for now.  
Fixes #1616 
> PR lower dashboard launch timeout

- nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterlab/overrides.json
Remove the following popup
```shell
jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
```
and
```json
{
"@jupyterlab/apputils-extension:notification": {
"fetchNews": "false"
}
}
```
> Feature remove jupyterlab news

- nebari/provider/cicd/github.py
- nebari/schema.py
Closes https://github.com/nebari-dev/nebari/issues/1671
This is required for Quansight's move towards oidc github-actions authentication.
> Feat GitHub actions before_script and after_script steps

- nebari/provider/cicd/github.py
Related to the need for OIDC support when deploying nebari see issue 
https://github.com/nebari-dev/nebari/issues/1671
This adds the following lines to the render for github
```yaml
permissions:
id-token: write
contents: read
```
To the github actions pipeline. From a security perspective there are no risks I can see of adding id-token to the pipeline.
> Github Actions CI needs id-token write permissions

- scripts/aws-force-destroy.sh
As part of the work to fix the integration tests, we need to make sure that all the cloud resources are always destroyed. AWS has consistently been the trickiest cloud provider in this regard. This is because individual resources need to be manually deleted if anything with `nebari destroy` goes wrong. 
I am continuing the work I started a few weeks ago and cleaning up this script, most notably ensuring that any lingering volumes are also destroyed.
> Update AWS force destroy script, include lingering volumes

- nebari/schema.py
- nebari/stages/input_vars.py
- nebari/template/stages/07-kubernetes-services/jupyterhub.tf
- nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/configmaps.tf
- nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_notebook_config.py.tpl
- nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/variables.tf
- nebari/template/stages/07-kubernetes-services/variables.tf
Closes #1283 
This PR makes it so users can configure the JupyterLab idle-culler settings directly from their `nebari-config.yaml`. The pattern that I used to achieve this was with a Terraform [templatefile](https://developer.hashicorp.com/terraform/language/functions/templatefile), which is a pattern that I believe we can use to modify other configuration files in the future (this might include the `.bashrc` and similar files). 
I still need to add documentation for this but to change the idle-culler settings, you can add the following to your `nebari-config.yaml`:
```yaml
jupyterlab:
idle_culler:
server_shutdown_no_activity_timeout: 100
kernel_cull_connected: true
```
Any subset of the idle culler settings can be configured like this. By default, the `jupyterlab` key is not included. …
> Make idle culler settings configurable from the `nebari-config.yaml`

- .github/workflows/release.yaml
Fetch PyPI secrets from Vault instead of relying on GitHub repo secrets.
> Pull PyPI secrets from Vault

- .github/workflows/kubernetes_test.yaml
- .github/workflows/test.yaml
Per title. Although we definitely want verbose output in CI, `--quiet` is actually harmless:
```
$ conda install --help | grep -e '--quiet'
-q, --quiet           Do not display progress bar.
```
So this just disables just the progress bars, which create quite a few unnecessary lines. For example: https://github.com/nebari-dev/nebari/actions/runs/4621921970/jobs/8173947067#step:4:646
> Use --quiet flag for conda install in CI

- tests/test_cli.py
Our current CLI tests are not sufficient, since our checking logic does not do what it is supposed to be doing. We only catch errors in the subprocess:
https://github.com/nebari-dev/nebari/blob/daecbcf37497b1b8b4e3f0f52667ababf3c023ad/tests/test_cli.py#L15-L23
However, `subprocess.call` does not fail on exit codes > 0:
```bash
$ ls foo
"foo": No such file or directory (os error 2)
$ echo $?
2
$ python -c 'import subprocess; subprocess.call(["ls", "foo"])'
ls: cannot access 'foo': No such file or directory
$ echo $?
0
```
This PR uses [`subprocess.run`](https://docs.python.org/3/library/subprocess.html#subprocess.run) instead, which is the [recommended way](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module) and has the `check=True` flag to enable error code …
> improve CLI tests

- nebari/cli/main.py
Fixes #1719.
This could be considered BC breaking, but I feel that would be a tad too much.
> use -V (upper case) for --version short form

- nebari/render.py
As discussed offline, per title. 
> remove lazy import

- .github/workflows/release-notes-sync.yaml
> Update secret token in release-notes-sync action

- RELEASE.md
Tiny fix to heading hierarchy for better presentation here: https://www.nebari.dev/docs/references/RELEASE
> Updating heading format in release notes

- .github/workflows/contributor.yaml
As seen in #1711 neither my maintainer status nor @iameskild's comment triggered the contributor tests. However, they are required by our branch protection rules. Meaning, #1711 is effectively stuck right now and cannot be merged. 
As explained in https://github.com/nebari-dev/nebari/pull/1734#issuecomment-1517695618, it is a pain to debug workflows that trigger on comments since they don't use the workflow file from the current PR, but only the one from the default branch. Thus, we probably need to merge this PR and try afterwards. I did that in my fork and it worked.
This PR does two things:
1. Instead of having one large condition, it is split in multiple atomic ones. Since we `&&` them together anyway, this can be trivially achieved.
2. Instead of having an `if:` trigger on multiple …
> Fix? contributor test trigger

- nebari/cli/init.py
It now requires user to press the Enter key after entering y/N as a choice.
#1742 
- [x ] New feature (non-breaking change which adds a feature)
- [x ] Did you test the pull request locally?
> Consistent user Experience with y/N.

- .github/workflows/contributor.yaml
It seems neither [I](https://github.com/nebari-dev/nebari/actions/runs/4854764166/jobs/8652518957#step:5:5) nor [@iameskild](https://github.com/nebari-dev/nebari/actions/runs/4854748098/jobs/8652486760#step:5:5) have permissions to trigger the contributor tests through a bot comment. Most likely, our check is not set up properly. This PR adds some debug outputs so we can see what role we actually need to check for.
> add more debug output to contributor test trigger

- nebari/upgrade.py
This was introduced in #1639.
This added a [warning to our tests](https://github.com/nebari-dev/nebari/actions/runs/4811511230/jobs/8565595846#step:5:29), but as predicted in https://github.com/nebari-dev/nebari/pull/1700#discussion_r1160669973, it was not caught. We should revisit treating all warnings as errors during testing.
https://github.com/nebari-dev/nebari/actions/runs/4811511230/jobs/8565595846#step:5:29
> fix invalid escape sequence

- .github/workflows/run-precommit.yaml
- nebari/template/stages/01-terraform-state/aws/main.tf
The comment
https://github.com/nebari-dev/nebari/blob/ac981ea6fe535cdc4592bffd60a49fe9ab137028/.github/workflows/run-precommit.yaml#L22-L23
is not the full picture. The action also [installs `pre-commit` and runs it against all files by default](https://github.com/pre-commit/action/blob/5f528da5c95691c4cf42ff76a4d10854b62cbb82/action.yml#L11-L20). Meaning, we are currently installing `pre-commit` for nothing 
https://github.com/nebari-dev/nebari/blob/ac981ea6fe535cdc4592bffd60a49fe9ab137028/.github/workflows/run-precommit.yaml#L25-L26
and running the `terraform_fmt` hook twice:
https://github.com/nebari-dev/nebari/blob/ac981ea6fe535cdc4592bffd60a49fe9ab137028/.github/workflows/run-precommit.yaml#L28-L29
This PR improves this by only running the `terraform_fmt` hook through the action.
> improve pre-commit run on GHA

- tests/test_dependencies.py
This PR adds `--channel=conda-forge` explicitly to the `conda build` we are running as part of our tests. Right now our CI relies on this being set in the `conda` configuration file:
https://github.com/nebari-dev/nebari/blob/6b38c8c3215b3ce7683b4c83fe2ecb9aa79c34ac/.github/workflows/test.yaml#L52
However, we cannot depend on this being the case locally for all other devs as well. Without setting the channel explicitly, `conda build` will try to pull from the `defaults` channel and fail, since it doesn't contain everything we need.
> use conda forge explicitly in conda build test

- .github/workflows/infracost.yml
- .github/workflows/test-provider.yaml
- .github/workflows/test.yaml
It is really annoying to see a large matrix completely cancelled just because one job failed. For example: https://github.com/nebari-dev/nebari/actions/runs/4981394220/jobs/8915592409. This is especially true, if the individual parameters aren't strongly correlated. For example, if tests fail on Python 3.8 it is likely that they also fail on 3.9. In contrast, if the provider test fails on AWS, this gives very little insight if the same would also fail on GCP or the like.
Thus, unless we have very strict budget concerns here, it would improve DevX quite a bit to not fail the matrix builds fast. The infracost CI has `fail-fast: true` set, but there is no comment in the PR that added it (#1316) as for why.
> don't fail CI matrices fast

- .cirun.yml
- .github/workflows/kubernetes_test.yaml
This would first try to spinup spot instance and if that fails then will spinup on-demand instance.
To save CI costs this would first try to spinup spot instance first and if that fails then will spinup on-demand instance.
See https://docs.cirun.io/reference/fallback-runners#example-3-preemptiblenon-preemptible-instances
> Spinup spot instance for CI with cirun

- src/_nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
When launching a jupyterlab server, user's in the `analyst` group (and not in the `developer`/`admin` groups) run into the following error: 
```
Error: secret "argo-view.service-account-token" not found
```
This is due to a mislabeling of the `argo-viewer` service account token.
> Fix argo-viewer service account reference

- src/_nebari/template/stages/01-terraform-state/do/main.tf
- src/_nebari/template/stages/01-terraform-state/do/modules/spaces/versions.tf
- src/_nebari/template/stages/01-terraform-state/do/modules/terraform-state/versions.tf
- src/_nebari/template/stages/02-infrastructure/do/modules/kubernetes/versions.tf
- src/_nebari/template/stages/02-infrastructure/do/modules/registry/versions.tf
The current provider was causing 404 (bucket not found error) too often, even though the bucket was present.
Ideally we should have this version only at one place, but not doing that change in this PR, to avoid too much conflict for Extension mechanism PR.
This has been tested here: https://github.com/nebari-dev/nebari/actions/runs/5756197370/job/15605162909
> Bump DigitalOcean provider to latest

- src/_nebari/initialize.py
- src/_nebari/provider/git.py
Bug fix: the `path` object is assumed to be a `pathlib.Path` object. This fix ensure that this is indeed the case.
> Ensure path is Path object

- src/_nebari/render.py
- src/_nebari/stages/terraform_state/template/aws/main.tf
- src/_nebari/stages/terraform_state/template/aws/modules/terraform-state/main.tf
- src/_nebari/subcommands/validate.py
Fixes #1914 
*Technically* fixes the issue, but more of a workaround
> workaround for mixed string/posixpath error

- src/_nebari/provider/cloud/amazon_web_services.py
- src/_nebari/stages/infrastructure/__init__.py
close #1917 
`check_credentials` is called before those functions, so the `AWS_DEFAULT_REGION` environment variable is always available when boto3 client is initialized.
> ENH: Remove aws cli, use boto3

- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/stages/terraform_state/__init__.py
- src/_nebari/stages/tf_objects.py
- src/_nebari/utils.py
Allow users to specify (via the nebari-config.yaml) which Azure Resource Group they deploy into. This also tries to preserve backward-compatibility so if nothing is provided, the default (current) behavior will be the same.
> Allow users to specify the Azure RG to deploy into

- tests/tests_unit/cli_validate/aws.error.kubernetes-version.yaml
- tests/tests_unit/cli_validate/aws.happy.yaml
- tests/tests_unit/cli_validate/azure.happy.yaml
- tests/tests_unit/cli_validate/do.happy.yaml
- tests/tests_unit/cli_validate/gcp.happy.yaml
- tests/tests_unit/cli_validate/local.error.extra-fields.yaml
- tests/tests_unit/cli_validate/local.error.project_name.yaml
- tests/tests_unit/cli_validate/local.happy.yaml
- tests/tests_unit/cli_validate/min.happy.yaml
- tests/tests_unit/test_cli_init.py
- tests/tests_unit/test_cli_validate.py
> nebari validate unit tests

- src/_nebari/upgrade.py
- tests/tests_unit/test_cli_upgrade.py
#1862 
Fixes #1961 
Fixes #1962
> nebari upgrade CLI tests

- src/_nebari/keycloak.py
- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/subcommands/dev.py
- src/_nebari/subcommands/support.py
- tests/tests_unit/test_cli_dev.py
- tests/tests_unit/test_cli_init.py
- tests/tests_unit/test_cli_keycloak.py
- tests/tests_unit/test_cli_support.py
- tests/tests_unit/test_cli_upgrade.py
- tests/tests_unit/test_cli_validate.py
- tests/tests_unit/test_render.py
> nebari cli environment variable handling, support, keycloak, dev tests

- src/_nebari/stages/bootstrap/__init__.py
- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/stages/kubernetes_ingress/__init__.py
- src/_nebari/stages/kubernetes_initialize/__init__.py
- src/_nebari/stages/kubernetes_keycloak/__init__.py
- src/_nebari/stages/kubernetes_keycloak_configuration/__init__.py
- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/nebari_tf_extensions/__init__.py
- src/_nebari/stages/terraform_state/__init__.py
xref #1800
Solution reference: https://docs.python.org/3/library/typing.html#the-type-of-class-objects
> TYP: fix return class type in hookimpl

- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/argo-workflows.tf
- src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
- src/_nebari/stages/kubernetes_services/template/variables.tf
> Do not try and add argo envs when disabled

- src/_nebari/stages/kubernetes_keycloak/__init__.py
- src/_nebari/upgrade.py
- tests/tests_unit/cli_validate/local.error.authentication-type-called-custom.yaml
- tests/tests_unit/test_cli_init.py
- tests/tests_unit/test_cli_upgrade.py
Fixes #1934 
Removes the `custom` auth provider option from the config schema. Includes unit tests to cover the upgrade path that was intended to handle the removal of this previously.
> remove custom auth from config schema

- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub-ssh/sftp.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub-ssh/ssh.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub-ssh/variables.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/kbatch/versions.tf
> Upgrade images for jupyterhub-ssh, kbatch

- .github/workflows/generate_cli_doc.yml
The API docs PR introduced a workflow to check for changes to the CLI, and if changes exist, that workflow will open a PR against the nebari-docs repo. This PR simply gives the workflow the required permissions to create this PR.
> Add permissions to generate_cli_docs workflow

- src/_nebari/provider/cloud/google_cloud.py
> ENH: specify required fields when retrieving available gcp projects

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/values.yaml
Fixes #1965 
Having the CHP networkPolicy enabled for JupyterHub deployed to AWS, Azure and GCP was no trouble so I'm not sure why this only seems to affect Digital Ocean. We also have the networkPolicy disabled for `hub` and `singleuser` already. 
We should definitely test this change on the other clouds before merging - I don't expect this to cause problems since removing the network policy makes internal networking more permissible.
> Modify JupyterHub networkPolicy to match existing policy

- .github/workflows/test_do_integration.yaml
> CI: add do integration

- src/_nebari/initialize.py
Current link https://www.nebari.dev/docs throws 404 and https://www.nebari.dev/docs/welcome works
> Fix link to documentation on Nebari Deployment home page

- .github/workflows/test.yaml
- pyproject.toml
xref: #1128
The original goal of this PR is to reduce the installation time. But then I discovered that we were not really testing multiple Python versions. When the CI is configured correctly, the Python 3.12 build from #2046 will not work due to the lack of wheels for `conda-build` and multiple other dependencies for Python 3.12.
In this PR, I reverted #2046, fixed the unit test build so it actually ran on different Python versions, added auto cancelation, and reduced the installation time from ~20min to ~ 1min.
> CI: improve unit test workflow in CI, revert #2046

- src/_nebari/upgrade.py
- tests/tests_unit/test_cli_upgrade.py
#2015 
- [X ] Build related changes
- [X ] Did you test the pull request locally?
Minor changes to CLI upgrade command and related tests since version of release is now 2023.10.1
> Update upgrade for 2023.10.1

- src/_nebari/stages/infrastructure/__init__.py
- tests/tests_unit/test_schema.py
close #2086
xref #2064
the bug was introduced in #2056 
> BUG: fix incorrect config override #2086

- src/_nebari/subcommands/init.py
> CLN: cleanup typing and typing import in init

- src/_nebari/upgrade.py
> Update upgrade instructions for 2023.11.1

- src/_nebari/stages/kubernetes_keycloak/template/modules/kubernetes/keycloak-helm/values.yaml
#2163
Deployment failures because of outdated busybox images.
Checking locally to verify the findings:
- With: `busybox:1.31`
```bash
$ docker run -it busybox:1.31 wget https://github.com/ 
Connecting to github.com (140.82.121.3:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
```
- And with `busybox:1.36.1`: 
```bash
$ docker run -it busybox:1.36.1 wget https://github.com                   
Connecting to github.com (140.82.121.3:443)
wget: note: TLS certificate validation not implemented
saving to 'index.html'
index.html           100% |************************************************************************************|  203k  0:00:00 ETA …
```
> Update busybox image tag version

- .pre-commit-config.yaml
- src/_nebari/stages/kubernetes_ingress/__init__.py
#2164 
Fix logic for matching the domain IP. 
> Fix logic for dns lookup.

- src/_nebari/stages/infrastructure/template/local/main.tf
- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/01-theme.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/values.yaml
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
- src/_nebari/stages/kubernetes_services/template/variables.tf
#2011 
Basic Installation docs: https://github.com/nebari-dev/nebari-docs/pull/391
> Integrate JupyterHub App Launcher into Nebari

- src/_nebari/stages/infrastructure/template/aws/main.tf
The permissions boundary was not passed in properly, as a result you'd see AccessDenied exception, when creating roles without the given permissions boundary.
Fixes #2152 
> Pass in permissions boundary to k8s module

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
At the moment it returns all the environments even if the user doesn't have access to it.
Ref: https://github.com/nebari-dev/jhub-apps/issues/51
> JHub Apps: Filter conda envs by user

- src/_nebari/upgrade.py
> update upgrade command

- src/_nebari/stages/kubernetes_keycloak_configuration/template/main.tf
Closes #2180
This PR uses the lifecycle.ignore_changes terraform attrribute which allows setting terraform to ignore if certain attributes are modified. I have tested this locally to work.
ignore_changes also supports an `all` parameter but this would set terraform to ignore all attributes in the resource which we do not want.
> Adding fields to ignore within keycloak_realm

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterlab/overrides.json
closes #2190 
This removes the popup from showing up when the user spawns its JupyterLab instance, more details in the corresponding issue.
Tested on a local version deployment of Nebari (based on Dev)
> Disable "Newer update available" popup as default setting

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
closes #2133 
This update adds a blocking configuration (globally applied) to the pip command, where its usage will only be habilitated if the user uses a ` virtualenv,` which we can assume the user will not attempt as we already provide the conda environments for such needs.
As an environment variable controls this, it's still possible to be overridden by the user if the variable's value is modified.
Tested within a local deployment:
- from within a notebook:
- from terminal:
obs.: tested within all envs to make sure it was supplied as a global update
> Block usage of pip inside jupyterlab 

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
For the time being, we'll return all the environments instead of just those under the user's namespace for jhub-apps. In the future, we'd like to expose a way of filtering all the environments a specific user has access to from conda-store.
#2193 
> Return all environments instead of just those under the user's namespace for jhub-apps

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/server.tf
Closes #2186
I have tested this forward upgrade from an older conda-store image. Love the new UI upgrade! 
This change is required from https://github.com/conda-incubator/conda-store/pull/639 and we are just creating the directory ahead of time which the server tries to create (it is not actually used by the server)
> Adding a temporary writable directory for conda-store server /home/conda

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/01-theme.py
This PR change the order in which the theme values are applied. Currently the theme default values take priority.
> Make it so that jhub-apps default theme doesn't override

- src/_nebari/stages/kubernetes_services/__init__.py
This PR exposes all the options for theming that are available in the current jhub-apps
> Adding additional theme variables to jupyterhub theme config

- .github/workflows/test_local_integration.yaml
- tests/common/navigator.py
- tests/common/playwright_fixtures.py
- tests/common/run_notebook.py
- tests/tests_deployment/test_jupyterhub_ssh.py
- tests/tests_deployment/utils.py
- tests/tests_e2e/playwright/test_playwright.py
> Modify Playwright test to account for changes in JupyterLab UI.

- pyproject.toml
The Jupyter Notebook tests that used `jhub-client` were removed in #2232. This PR removes `jhub-client` as a dependency, because I don't believe we use it anywhere else.
> Remove `jhub-client` from pyproject.toml

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/extras/git_clone_update.sh
> Include permission validation step to programmatically cloned repos

- .github/workflows/test_local_integration.yaml
- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/configmaps.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
- tests/tests_e2e/cypress/integration/main.js
- tests/tests_unit/cli_validate/min.happy.jupyterlab.default_settings.yaml
Closes #2247
No, I could not setup nebari locally due to `Error: client rate limiter Wait returned an error: context deadline exceeded` error
Yes, I added a new config yaml file for happy path verifying that `jupyterlab.default_settings` does not error out, and an end-to-end test
> Allow to configure default settings for JupyterLab (`overrides.json`)

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/configmaps.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_jupyterlab_pioneer_config.py.tpl
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_server_config.py.tpl
> Fix syntax error in jupyter-server-config Python file

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterlab/overrides.json
Together with https://github.com/nebari-dev/jupyterlab-nebari-mode/pull/1 fixes https://github.com/nebari-dev/nebari/issues/2217
See integration tests in https://github.com/nebari-dev/jupyterlab-nebari-mode/pull/1.
-
> Add "Open VS Code" entry in services

- src/_nebari/stages/kubernetes_keycloak/template/modules/kubernetes/keycloak-helm/values.yaml
- src/_nebari/stages/kubernetes_services/__init__.py
Fixes https://github.com/nebari-dev/nebari/issues/2311.  We should test how this will affect users upgrading Nebari.  Ideally, the images are identical so there is no ill effects, but that may not be the case.
> update keycloak image repo

- scripts/helm-validate.py
[This](https://github.com/nebari-dev/nebari/actions/runs/8272452121/job/22634293608) part of the release process was failing with error `ValueError: Could not find loki:{'description': 'version to deploy for the loki helm chart', 'type': '${string}', 'default': '5.43.3'} directory in helm_charts.`.  chart_version was being set to `{'description': 'version to deploy for the loki helm chart', 'type': '${string}', 'default': '5.43.3'}` instead of '5.43.3'.  This became an issue with the recent addition of loki.
I tested the change locally and it seems to run fine.  I'm not sure if there are other use cases where we would not want to grab the default value, but it does seem to run successfully when I run it locally.  Asking @viniciusdc to review since I believe he originally implemented this …
> get default variable value when following a terraform variable

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/monitoring/main.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/monitoring/values.yaml
It was accidentally assumed that Nebari will always be deployed on "dev" namespace, hence the constructed loki gateway url was not correct for non dev namespaces. This PR makes sure to incorporate namespace in gateway url.
> Fix loki gateway url when deployed on non-dev namespace

- pyproject.toml
> upgrade auth0-python version to ultimately resolve CVE-2024-26130

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterlab/overrides.json
- Fixes #2326.
- Depends on https://github.com/nebari-dev/nebari-docker-images/pull/130
Uses `jupyterlab-conda-store` if available, fallbacks to opening `/conda-store` in new browser tab otherwise. The label in each case is set to "Environment Manager" (but we can adjust it).
- "Services > Environment Management" coming from nebari and opening conda-store in a new tab:
- "Conda-Store > Conda Store Package Manager" coming from `jupyterlab-conda-store`:
- single "Services > Environment Manager" which opens `jupyterlab-conda-store` if available or `/conda-store` in new tab otherwise.
> Deduplicate conda-store in JupyterLab main menu

- RELEASE.md
- src/_nebari/constants.py
> Update release notes for 2024.3.3

- src/_nebari/stages/infrastructure/template/azure/versions.tf
- src/_nebari/stages/terraform_state/template/azure/main.tf
Fixes https://github.com/nebari-dev/nebari/issues/2374
Azurerm was throwing the following error on deployment in eastus2 region when updating a cluster from 2024.1.1 to 2024.3.3.
```
Error: retrieving Cluster: (Managed Cluster Name "nebari-dev" / Resource Group "my-resourcegroup"): 
containerservice.ManagedClustersClient#Get: Failure respond ing to request: StatusCode=400 -- 
Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" 
Message="No registered resource provider found for location 'eastus2' and API version '2022-03-02-preview' for type 'managedClusters'.
```
Updating azurerm provider fixed the issue.
> update azurerm version

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- A task for https://github.com/nebari-dev/nebari/issues/2308
- Can be merged straightaway but for the `groups` to get populated from keycloak requires https://github.com/nebari-dev/nebari-docker-images/pull/131
To test:
1. Set the image to use https://github.com/nebari-dev/nebari-docker-images/pull/131:
```
default_images:
jupyterhub: quay.io/nebari/nebari-jupyterhub:oauthenticator-16.3.0
```
2. Deploy
3. Open https://your-nebari-deployment/hub/token
4. Open Dev Tools in your browser, switch to Network tab
5. Press "Request new API token"
6. Right click on the request in Network tab → copy as fetch
7. Paste the request, change method to "GET", remove "body", change URL to `/hub/api/users`
8. Re-send the request
9. Click on the new request, preview the …
> Get JupyterHub `groups` from Keycloak, support `oauthenticator` 16.3+

- src/_nebari/subcommands/init.py
Fixes #1708 
PR #1744 was made for this before and @iameskild had described [a good solution](https://github.com/nebari-dev/nebari/pull/1744/files#r1198403593), but the difficulties faced last time arose due to the fact that there's a pydantic root validator in place which then doesn't allow `inputs.cloud_provider` to store full cloud provider names outright. The feature can be implemented by simply using a new variable to hold the inputs from the user and then still passing the accepted enum vals on to `inputs.cloud_provider`.
It's a very very minor change!
- [ x ] Code style update (formatting, renaming)
- [ x ] Did you test the pull request locally?
> add full names for cloud providers in guided init

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/middleware.tf
> Add middleware to prefix JupyterHub navbar items with /hub.

- .github/workflows/test-provider.yaml
The cloud provider CI/CD test fails when run from forks of this repo which do not have credentials (and presumably, their own accounts) set up for the providers used by the test. This situation generates spurious CI/CD pipeline failure messages.
This PR adds the ability for repo fork maintainers to skip the CI/CD Cloud Provider Test by setting a repo variable 'NO_PROVIDER_CREDENTIALS'. If that variable is ***not set*** by the repo maintainer (the default case), the test behavior will be unchanged from before this PR.
> Make CI/CD Cloud Provider Test Conditional

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
Fixes https://github.com/nebari-dev/nebari/issues/2414
Tagging @pt247, I'm confident this won't affect the "dedicated" stuff for AWS that he implemented recently, but if @pt247 could give it a quick check over and confirm I'd appreciate it.  Thanks!
> make userscheduler run on general node group

- src/_nebari/stages/infrastructure/__init__.py
Fixes https://github.com/nebari-dev/nebari/issues/2425 associated with pydantic v1 vs v2 behavior.
> remove redundant pydantic class, fix bug

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
Fixes https://github.com/nebari-dev/nebari/issues/2437
There is a sister PR for the docs - https://github.com/nebari-dev/nebari-docs/pull/444
> add HERA_TOKEN env var to user pods

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
Fixes https://github.com/nebari-dev/nebari/issues/2436
Due to a recent change, adding `jupyterhub_admin` role to a user doesn't makes it admin for JupyterHub, this PR fixes that.
> Update allowed admin groups

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
Closes https://github.com/nebari-dev/nebari/issues/2330
This depends on https://github.com/nebari-dev/nebari-docker-images/pull/140.
> Upgrade to JupyterHub 5.0

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/04-auth.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/keycloak-client/main.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/keycloak-client/outputs.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/keycloak-client/variables.tf
- tests/tests_deployment/test_jupyterhub_api.py
Closes #2308
It is useful to think about this PR as having two parts:
- (a) when user logs in (or their cookie gets refreshed), we extract the roles list from the auth data to ensure that their roles are up to date (which is handled by JupyterHub)
- (b) when restarting JupyterHub we load all the roles and role assignments from Keycloak using Keycloak REST API; this is to prevent users from being stripped from role assignments because auth-managed roles are not meant to be persisted indefinitely in JupyterHub (by definition). Note, that we _could_ decide not to strip the roles at all, but then if an administrator accidentally grants an elevated role to a user in Keycloak, the user would retain such a role forever (until manually modified in JupyterHub database).
_Put a `x` in the boxes …
> Fetch JupyterHub roles from Keycloak

- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/upgrade.py
Fixes https://github.com/nebari-dev/nebari/issues/2452
> Reduce GCP Fixed Costs by 50%

- tests/common/navigator.py
- tests/common/run_notebook.py
Fixes #2473
Let's hope the CI passes!
> Fix test using a non-specific selector

- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/forward-auth.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/forwardauth/main.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/forwardauth/variables.tf
Fixes https://github.com/nebari-dev/nebari/issues/2478 for existing certs (though it doesn't fix traefik's default self-signed cert)
> fix forward auth when using custom cert

- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/upgrade.py
This is a companion PR to https://github.com/nebari-dev/nebari/pull/2453.  B/c we don't yet know for sure the next version of Nebari will be 2024.5.2, I've added this PR to be corrected and merged shortly before the next release of Nebari.
> upgrade instructions for PR 2453

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/04-auth.py
- tests/tests_deployment/conftest.py
- tests/tests_deployment/keycloak_utils.py
- tests/tests_deployment/test_jupyterhub_api.py
- tests/tests_deployment/utils.py
> Parse and insert keycloak roles scopes into JupyterHub

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
VSCode is now added by default to the new JHub Apps/App Launcher side navigation. This update, in addition to Nebari providing a default list of services for jhub_apps (which includes VSCode), is causing a duplicate entry in the side navigation.
This PR removes VSCode from the default jub_apps configuration as it is not needed anymore and resolves the duplicate entry.
N/A
> Remove VSCode from jhub_apps default services

- src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/main.tf
Fixes https://github.com/nebari-dev/nebari/issues/2516
> fix general node scaling bug for azure

- pyproject.toml
- src/_nebari/upgrade.py
Should fix #1792 
This PR adds file-level documentation strings for `upgrade.py`
> 1792 Add docstrings to `upgrade.py`

- src/_nebari/stages/terraform_state/template/azure/modules/terraform-state/main.tf
> set's min TLS version for azure storage account to TLS 1.2

- src/_nebari/stages/kubernetes_ingress/__init__.py
There is no need for a sleep on trying DNS lookup unless you've disabled the prompt since it waits til you press Enter anyways.  This removes the sleep the case you haven't disabled prompts.
> remove dns sleep

- .github/workflows/test_local_integration.yaml
- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/config/conda_store_config.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/server.tf
- tests/common/conda_store_utils.py
- tests/tests_deployment/conftest.py
- tests/tests_deployment/test_conda_store_roles_loaded.py
Fixes #2433 #2490
Docs: https://github.com/nebari-dev/nebari-docs/pull/480
Rendered link: https://deploy-preview-480--nebari-docs.netlify.app/docs/how-tos/fine-grained-permissions
This achieves the following two things:
- Uses conda-store's v2 of RBACAuthorizationBackend
- Parses and loads conda-store roles from keycloak
This PR basically lets you assign conda-store roles to users/groups from keycloak:
The following role when applied to a group or user will give the users in group /user "viewer" access to namespace "aktech":
> Conda-store permissions v2 + load roles from keycloak

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/04-auth.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/keycloak-client/main.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/keycloak-client/variables.tf
- tests/tests_deployment/keycloak_utils.py
- tests/tests_deployment/test_jupyterhub_api.py
> Add a default roles at initialisation

- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
Accompanies https://github.com/nebari-dev/jupyterlab-gallery/pull/20
> Hide gallery section if no exhibits are configured

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
- tests/tests_deployment/test_jupyterhub_ssh.py
Fixes https://github.com/nebari-dev/nebari/issues/1899
> stop copying unneccesary files into user home directory

- src/_nebari/subcommands/deploy.py
- src/_nebari/subcommands/init.py
closes #2565
- Adds a new message while selecting the available options during `guided-init` to inform the user that Digital Ocean (DO) support is being deprecated.
- Includes a confirmation message when deploying clusters of DO, warning of the deprecation
> Include deprecation notes for init/deploy subcommands

- src/_nebari/stages/tf_objects.py
We were using an experimental feature requiring the experiment be explicitly added, but it is no longer experimental as of [version 2.6.0](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md#260-october-19-2021) release.  We currently use version 2.20.0 of the kubernetes terraform provider.
> remove unnecessary experimental flag

- .pre-commit-config.yaml
- pyproject.toml
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/monitoring/dashboards/Main/conda_store.json
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/monitoring/dashboards/Main/keycloak.json
- Concentrates codespell configuration in pyproject.toml instead of pre-commit configuration so user could simply run `codespell` and get it all clean
- Do codespell .json files (but not package-lock.json)
- Two typos fixed 
- Highly related: https://github.com/nebari-dev/nebari/pull/2568 . Apparently more typos to add to codespell ;-)
TODOs:
> Improve codespell support: adjust and concentrate config to pyproject.toml and fix more typos

- .pre-commit-config.yaml
The codespell config was added to pyproject.toml in https://github.com/nebari-dev/nebari/pull/2583.  This allows users to run `codespell` from command line and pick up the config as well as be picked up by pre-commit.  Typos config is already in pyproject as well since some options couldn't be set via command line.
I think we should move the codespell config there exclusively so we don't have to update things in 2 places.  The only difference is we still want --write on pre-commit, but not when using codespell from command line.
> Move codespell config to pyproject.toml only

- src/_nebari/stages/infrastructure/template/aws/modules/s3/main.tf
- src/_nebari/stages/terraform_state/template/aws/modules/terraform-state/main.tf
#2613 
If a PutBucketEncryption call is made to AWS to apply server-side encryption configuration just after an S3 bucket is created, AWS may return an HTTP 409 (Conflict) error with an OperationAborted error code. By making `aws_s3_bucket_server_side_encryption_configuration` explicitly dependent on `aws_s3_bucket_public_access_block`, we guarantee two things:
- The encryption will not run concurrently as it now needs to wait for the public access block to succeed;
- It will not run directly after the bucket creation, giving us enough time for the requests to correctly process.
Below, we can see a graph representing the resource dependencies; the object associated with the arrowhead has priority over the others.
Before the `depends_on` tag:
After the dependency was set:
_Put a `x` in the …
> Add `depends_on` for bucket encryption

- src/_nebari/stages/infrastructure/__init__.py
Fixes #2128 
Ran into this bug again when trying to update our deploymen to 24.6.1, I guess we are one of the few deploying to "existing" infrastructure. Then after an hour of troubleshooting learned that I already had created a bug report for this. Here is the PR to hopefully have it fixed in the newer versions!
> Fix: KeyValueDict error when deploying to existing infrastructure

- src/_nebari/stages/kubernetes_services/template/conda-store.tf
- src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
Fixes https://github.com/nebari-dev/nebari/issues/2638
Uses [moved blocks](https://developer.hashicorp.com/terraform/language/modules/develop/refactoring#enabling-count-or-for_each-for-a-resource) to account for refactored terraform code.
I've tested on the following deployments.
> add a "moved" block to account for refactored terraform code without deleting/recreating NFS disks

- src/_nebari/provider/terraform.py
- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/terraform_state/__init__.py
- src/_nebari/stages/tf_objects.py
- src/_nebari/utils.py
- src/nebari/schema.py
- tests/tests_unit/test_stages.py
- tests/tests_unit/test_utils.py
Fixes https://github.com/nebari-dev/nebari/issues/2607
Probably best to start with src/_nebari/stages/terraform_state/__init__.py on the PR Reviews.
I decided to add the immutability check at the beginning of Stage 01 instead of between Stage 01 and Stage 02 as originally described in https://github.com/nebari-dev/nebari/issues/2607#issue-2443619771.
> Support disallowed nebari config changes

- src/_nebari/subcommands/init.py
Closes #2664 
Run `nebari init --guided-init` and answer the prompts as following:
```
Welcome to the Guided Init wizard!
You will be asked a few questions to generate your nebari-config.yaml. For more
details, refer to the Nebari docs:
https://nebari.dev/docs/
🪴  Nebari runs on a Kubernetes cluster: Where do you want this Kubernetes
cluster deployed? is where you want this Kubernetes cluster deployed. For more
details, refer to the Nebari docs:
https://nebari.dev/docs/get-started/deploy
❗️ local requires Docker and Kubernetes running on your local machine.
Currently only available on Linux OS.
❗️ existing refers to an existing Kubernetes cluster that Nebari can be
deployed on.
❗️ Digital Ocean is currently being deprecated and support will be
removed …
```
> Fix converted init command in guided init

- src/_nebari/provider/terraform.py
- src/_nebari/utils.py
I accidentally was trying to parse stdout + stderr as json instead of just stdout when capture_output=True.  This PR fixes that.
Fixes failing deployment tests
- e.g. https://github.com/nebari-dev/nebari/actions/runs/10658945768
I validated the idea by re-running one of them and it worked - https://github.com/nebari-dev/nebari/actions/runs/10689796315
Azure now seems to be failing for an unrelated reason - https://github.com/nebari-dev/nebari/actions/runs/10691605764
GCP redeployment - https://github.com/nebari-dev/nebari/actions/runs/10691927249
Do a local deployment with the "TF_LOG" env var set to "TRACE"
> only capture stdout not stdout+stderr when capture_output=True

- .github/workflows/test_azure_integration.yaml
https://github.com/nebari-dev/nebari/pull/2632 removed a few credentials on the Azure deployment test which now fails with
```
Error building ARM Config: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
```
This PR reverts the changes to the credentials.  
If [this](https://github.com/nebari-dev/nebari/actions/runs/10706057961/job/29682871900) finishes successfully then it verifies this is the fix for the issue.
> revert breaking change to azure deployment test

- src/_nebari/stages/terraform_state/__init__.py
- tests/tests_unit/test_stages.py
Fixes https://github.com/nebari-dev/nebari/issues/2719
- Run new tests before fix and see them fail([26a2f2b](https://github.com/nebari-dev/nebari/pull/2724/commits/26a2f2b6f32ae95737d1e4b52b02e0ac71f7f3b5))
- Run new tests after fix and see them pass ([latest commit](https://github.com/nebari-dev/nebari/pull/2724/commits/a44c1083f9ab48015915212314da463e94925777))
> add test for changing dicts and lists

- src/_nebari/upgrade.py
Fixes https://github.com/nebari-dev/nebari/issues/2640
Related to https://github.com/nebari-dev/nebari/issues/2725
> 2024.9.1 upgrade notes

- src/_nebari/provider/terraform.py
- src/_nebari/stages/base.py
- src/_nebari/stages/terraform_state/__init__.py
Closes #2732 
1. Install `nebari==2024.7.1`
2. Go through the guided init, making sure a GitHub repo is initialized for the Nebari deployment
3. Deploy Nebari
4. Install Nebari from this branch running:
```bash
pip install git+https://github.com/nebari-dev/nebari.git@run-init-before-show
```
5. Upgrade Nebari
6. Render the files
7. Make sure the `.github/workflows/nebari-ops.yaml` file installs Nebari from this branch
8. Commit and push the changes and let GHA run the re-deployment
Shout-out to @dcmcand and @viniciusdc for helping me with this solution
> Run terraform init before running terraform show

- tests/tests_deployment/test_dask_gateway.py
There seems to be an issue with how dask or `aiohttp` calls the underlying proxy connector (that's decided based on the URL schema passed down as a parameter), which has changed recently. This is breaking our unit tests recently, this PR proposes a change to disable ssl checks made by the gateway client when running locally. 
closes #2744
> Test implict aiohttp's TCP to HTTP connector change

- src/_nebari/keycloak.py
- src/_nebari/upgrade.py
- tests/tests_unit/test_upgrade.py
> Add compatibility prompt and notes for shared group mounting

- .github/ISSUE_TEMPLATE/release-checklist.md
- .github/workflows/test_aws_integration.yaml
- .github/workflows/test_azure_integration.yaml
- .github/workflows/test_do_integration.yaml
- .github/workflows/test_gcp_integration.yaml
- .github/workflows/test_local_integration.yaml
- .github/workflows/trivy.yml
Closes https://github.com/nebari-dev/nebari/issues/2665
Related PR on docs repo: https://github.com/nebari-dev/nebari/pull/2748
I don't have permissions to make sure the branch protection rules are moved over to main.  @dcmcand or @dharhas can you either give me permissions in the repo or check on that yourself?
> handle branch rename from develop to main in github actions

- .github/workflows/run-precommit.yaml
- .github/workflows/test-provider.yaml
- .github/workflows/test_aws_integration.yaml
- .github/workflows/test_azure_integration.yaml
- .github/workflows/test_conda_build.yaml
- .github/workflows/test_gcp_integration.yaml
- .github/workflows/test_local_integration.yaml
- .github/workflows/typing.yaml
Closes #2770 
You can manually trigger any of the cloud deployment workflows (i.e., [AWS](https://github.com/nebari-dev/nebari/actions/workflows/test_aws_integration.yaml), [Azure](https://github.com/nebari-dev/nebari/actions/workflows/test_azure_integration.yaml) and [Google Cloud](https://github.com/nebari-dev/nebari/actions/workflows/test_gcp_integration.yaml)) and specify `main` as the Nebari branch in the first text box (not from the dropdown menu in the first item).
> Remove old develop branch references after default branch renaming

- .github/workflows/run-precommit.yaml
- src/_nebari/provider/cicd/github.py
We are experiencing a similar issue to https://github.com/pre-commit/action/issues/210.  This fixes the issue.
> fix CICD issue with pre-commit action

- src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/conda-store-healthcheck.yaml
- src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/jupyterhub-healthcheck.yaml
- src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/keycloak-healthcheck.yaml
- src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/kustomization.yaml.tmpl
Fixes #2776 
-  [X] Bug fix (non-breaking change which fixes an issue)
Change your namespace in your nebari-config.yaml and rerender your stages. The kuberhealthy manifests rendered in stage 11 should reflect the changed namespace in the `CHECK_URL` env var
> fix CHECK_URL in kuberhealthy checks to respect namespaces

- src/_nebari/stages/infrastructure/__init__.py
Fixes #2785
see that there is only one definition for the class.
> remove duplicate GCPPrivateClusterConfig class

- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
- src/_nebari/stages/kubernetes_services/template/variables.tf
Fixes #2753
Documentation PR: https://github.com/nebari-dev/nebari-docs/pull/534
This would be specially be useful to modify things like these:
https://github.com/nebari-dev/jhub-apps/pull/499
> Add ability to add overrides to jhub-apps config

- .github/workflows/test.yaml
See https://github.com/nebari-dev/nebari/issues/2770. I missed one reference on a previous PR: https://github.com/nebari-dev/nebari/pull/2769
> Remove leftover develop reference

- src/_nebari/stages/terraform_state/__init__.py
- tests/tests_unit/test_stages.py
Fixes https://github.com/nebari-dev/nebari/issues/2781
> fix bug where check_immutable_fields throws error with old version of Nebari

- src/_nebari/upgrade.py
closes #2766 
This issue is a patching fix for the upgrade command present in the previous release, currently the upgrade logic when requesting the user to perform the role creation (more details see linked issue), assumes the presence of the role when assigning it to the legacy groups. However, this leads to errors when the role does not exist or is within Terraform if the user attempts to manually address the missing role to continue the upgrade.
This PRs includes a new section in the previous code logic to create the role, and to avoid conflicts with terraform, I adopted a "legacy" prefix to the role name with a befitting description for future reference when the amdins manages keycloak in the future.  
- Perform any type of deployment for Nebari …
> Refactor role creation for upgrade command path

- src/_nebari/provider/cloud/google_cloud.py
- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/subcommands/init.py
Fixes #2822 
Allows specifiying either major and minor versions, major minor and patch versions, or full versions of kubernetes for gcp. Also changes guided init so that if no version is specified, the latest patch version is used.
1. Run either `nebari init --guided-init` and don't specify a kubernetes version or `nebari init gcp -p your_project_name -d your_domain_name.org` 
2.  To validate, you can deploy to GCP or locally using `1.X`, `1.X.X`, and `1.X.X-gke.x`
2. Use
> allow passing X.XX or X.XX.XX as k8s versions

- .github/workflows/test_aws_integration.yaml
- .github/workflows/test_azure_integration.yaml
- .github/workflows/test_gcp_integration.yaml
Closes #2836 
You won't be able to see the branch input textbox gone from the GitHub Actions UI until we merge the PR to main. However, you can compare this approach to our [local upgrade tests](https://github.com/nebari-dev/nebari/blob/855aa14ecc32625a98ec01b017acfc8a4af3c017/.github/workflows/test_local_upgrade.yaml), which don't specify the branch as an input and can still be run from an arbitrary branch:
> Remove explicit branch inputs from cloud integration test workflows in GHA

- src/_nebari/upgrade.py
> Allow overriding of keycloak root credentials for `2024.11.1` upgrade path

- src/_nebari/stages/infrastructure/__init__.py
This PR will disable the configuration of `node_groups.*.launch_template.ami_id` specifically, until #2832 is addressed. 
> Set `launch_template.ami_id` attrs to private

- src/_nebari/stages/infrastructure/__init__.py
This PR disables the user-facing object from the nebari-config schema while still keeping the logic introduced initially in #2621. 
The #2842 attempted to disable the `ami_id` setting from the `launch_template` configuration under the node groups. However, this change caused Terraform deployment issues because the aws node_group relied on the `ami_id` attribute internaly, leading to a failed Nebari deployments when it was removed in the linked PR.
Additionally, we've encountered recent internal connection issues with the nodes using just the `pre_bootstrap_command.` These issues indicated that the current configuration for `launch_template` is not functioning correctly.
It also includes:
- a custom error message in the schema validator for letting users know this is a temporary removal;
- …
> Disable AWS `launch_template` from nebari-config schema

- src/_nebari/provider/cloud/google_cloud.py
gcp provider tests are failing because the wrong google cloud client was used.
CI passes
> update gcp instance validation

- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/stages/infrastructure/template/azure/main.tf
- src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/main.tf
- src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/variables.tf
- src/_nebari/stages/infrastructure/template/azure/variables.tf
> Add azure kubernetes policy add-on

- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/stages/infrastructure/template/azure/variables.tf
Previous ENH PR #2888 included a bug with the default variable value for the `azure_addon_policy_enabled` setting. 
- Fixes the default value attr. for the recent addition while also including the missing field as a configurable option in the nebari-config.yaml schema. 
- 
> Handle default value for azure addon policy

- tests/common/handlers.py
This PR fixes the broken conda-store ui tests which look for the `Create Environment` button. This button was renamed in https://github.com/conda-incubator/conda-store-ui/pull/389 to just `Create`.
This test might have started breaking after updating conda-store from 2024.3.1 to 2024.11.1.
> Update conda-store-ui tests for updated page verbage

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
Previously, if the number of environments is less than the default pagination size, no environments are shown to the user when launching jhubb apps.
This change ensures that all conda environments are retrieved when the number of environments is less than the DEFAULT_PAGE_SIZE_LIMIT.
follow up to https://github.com/nebari-dev/nebari/pull/2910
0. To test this PR you must have
a. an installation of Nebari with jhub apps enabled
b. at least 100 conda-store environments (or decrease the size_limit var in the PR to a sufficiently small number, like 2)
1. Navigate to the nebari home screen
2. Click on the deploy app button
3. Click on the drop down to select the conda store environment for the app
4. Notice that all the environments are available
> [BUG] - Make sure to get envs when the number of envs is less than page limit

- .github/CODEOWNERS
Adds a CODEOWNERS file which will make the maintenance team the default reviewers for PR's
> add code owners file to make maintenance team default reviewers

- src/_nebari/stages/infrastructure/template/aws/modules/network/main.tf
closes #2882
This alert is because the security group has an egress rule that allows egress to `0.0.0.0/0`. Reference for the finding is at https://avd.aquasec.com/misconfig/aws/ec2/avd-aws-0104/
However, the nature of the type of work done in Nebari means that we need this rule, and since it is an egress rule we choose to accept this risk.
This PR causes trivy to ignore this finding for this resource. It is as narrowly scoped as possible so that if this rule finds other instances we can address them if needed.
Merge and check the security table.
> ignore trivy finding for public egress

- .cirun.yml
It's been a long overdue, we have been using ubuntu 20 as of today, which causes warnings like these:
Also our playwright installation is missing dependencies: https://github.com/nebari-dev/nebari/actions/runs/13273857606/job/37059318705#step:7:537
> Upgrade cirun AMI to ubuntu 24.04

- src/_nebari/stages/terraform_state/__init__.py
- src/_nebari/upgrade.py
- src/_nebari/utils.py
- deploy nebari to Azure with `2024.12.1`
- pip install from this branch, and run `nebari upgrade`
> Update Azure's schema changes during `2025.2.1` upgrade

- src/_nebari/utils.py
Deploy local.  This is what the logs look like at the end (see image).
Notice the green ansi coloring continues after tofu logs are complete.  This PR sets the ansi reset code at the end of the log capture fixing the issue.
After this fix they look like
Deploy locally, and see that the log coloring looks correct at the end of the deployment.
> fix ansi color reset bug

- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/main.tf
closes #2881 
adds ability to specify `aws.eks_public_access_cidr` in your nebari-config.yaml
Deploy to AWS
Go to the EKS console and under the `networking` tab, check that `Public access source allowlist` says `"0.0.0.0/0"`
add `eks_public_access_cidrs: ["{YOUR_PUBLIC_IP}/32"]` to your config under the AWS object
ex:
```
amazon_web_services:
kubernetes_version: '1.31'
region: us-east-2
eks_public_access_cidrs: ["12.345.678.910/32"]
node_groups:
general:
instance: m5.2xlarge
min_nodes: 1
max_nodes: 1
gpu: false
single_subnet: false
permissions_boundary:
user:
instance: m5.xlarge
min_nodes: 0
max_nodes: 5
gpu: false
single_subnet: false
permissions_boundary:
worker:
instance: m5.xlarge
min_nodes: 0
max_nodes: 5
gpu: false
single_subnet: false …
```
> allow eks_public_access_cidrs to be optionally set in nebari-config.yaml

- src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/argo-healthcheck.yaml
- src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/dask-gateway-healthcheck.yaml
- src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/grafana-healthcheck.yaml
- src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/kustomization.yaml.tmpl
- tests/tests_integration/test_all_clouds.py
closes #2976 
- add extra checks for argo, dask-gateway and grafana, 
> Add extra services checks to kuberhealthy

- .github/workflows/test_local_integration.yaml
- pyproject.toml
Fixes https://github.com/conda-incubator/conda-store/issues/1095 temporarily in Nebari
Make sure the conda-store user journey tests step in the local integration tests workflow are passing
> Pin conda-lock < 3.0.0 to fix conda-store user journey test failures

- src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/main.tf
Closes #3021 
Deploy Nebari to Azure and make sure it does not fail with:
```
[tofu]: │ Error: Unsupported argument
[tofu]: │ 
[tofu]: │   on modules/kubernetes/main.tf line 40, in resource "azurerm_kubernetes_cluster" "main":
[tofu]: │   40:     enable_auto_scaling = "true"
[tofu]: │ 
[tofu]: │ An argument named "enable_auto_scaling" is not expected here.
[tofu]: ╵
```
> Revert aks cluster argument to auto_scaling_enabled

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterlab/overrides.json
Companion PR: https://github.com/nebari-dev/nebari-docker-images/pull/219
Deploy Nebari from this branch using the JupyterLab image built by https://github.com/nebari-dev/nebari-docker-images/pull/219. Specify it in the Nebari config file as follows:
```yaml
default_images:
jupyterlab: quay.io/nebari/nebari-jupyterlab:upgrade-jupyterlab-c84ace5-20250516
```
Once Nebari is deployed, spawn a JupyterLab server, go to the Settings tab, and open the Settings Editor. Navigate to the Notebook section on the left panel, click on the JSOn Settings Editor Button on the upper right corner, and make sure `"windowingMode": "defer"` is on the System Defaults JSON, just like this:
> Change JupyterLab default windowing mode to defer

- src/_nebari/subcommands/deploy.py
- src/_nebari/subcommands/destroy.py
- src/_nebari/subcommands/render.py
Safety issue: https://github.com/nebari-dev/nebari/issues/1716
Until that issue is fixed and tested, IMO it is best to temporarily remove this feature.
> Remove --output/-o for now, it is not safe

- .github/workflows/test-provider.yaml
After #3103 got merged, we removed the `-o,-- output` flag from within our CLI commands, due to the possible harm it could lead to users' infrastructure. While we work on a new implementation of that flag, our render tests that used such an attribute need to be refactored to work without it. 
> Remove usage of `--output` flag within tests

- README.md
- tests/tests_unit/cli_validate/min.happy.certificate.yaml
- Updated README to reference the new nebari-slurm repository instead of the deprecated qhub-hpc repository
- Updated Code of Conduct link to point to nebari-dev organization
- Updated test email from quansight.com to openteams.com domain
> Update references from qhub-hpc to nebari-slurm and organizational updates

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
relates as a workaround for #3044 
This PR includes a list of supplemental group IDs (GIDs) to the NSS wrapper group files to dismiss the:
```shell
groups: cannot find name for group ID XX
```
Warning logs during terminal/kernel startups on users' JupyterLab instances. 
> Suppress missing GID warnings with supplemental groups

- src/_nebari/stages/bootstrap/__init__.py
- tests/tests_unit/conftest.py
- tests/tests_unit/test_bootstrap.py
Fixes #3104
When running `nebari render` my existing .gitignore was clobbered. If there is already a .gitignore, this step should be a no-op.
Use `nebari render` without a previously existing .gitignore, one should be created.
Use `nebari render` with a previously existing .gitignore, it should not be changed.
> bf: do not clobber existing .gitignore

- src/_nebari/cli.py
- tests/tests_unit/test_cli.py
There's currently no easy way to adjust the log level output from nebari commands.  This PR resolves that.
- Add `--log-level/-l` CLI option accepting debug, info, warning, error, critical levels
- Maintain detailed formatting for debug level with timestamps and module names
- Default to info level for optimal user experience
> Add configurable log level option to CLI
