nebari-dev/nebari

- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/apt.txt
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/postBuild
- Add apt packages
- Add jupyterlab extensions
> modify base qhub

- .github/workflows/image-pr.yaml
- .github/workflows/image.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/postBuild
Fixes https://github.com/Quansight/qhub/issues/75 partially.
> uncomment docker related workflows

- docs/docs/step-by-step-walkthrough.md
The existing text didn't work for us, but fixing thusly made it go
> Fixes typo in step-by-step

- docs/docs/step-by-step-walkthrough.md
Even more subtle changes fixing numbering for 1) to 1. and setting the environment variable in section 4. To be checked by the team if that makes sense  ... Ignore previous request.
> Jkellndorfer patch step by step 3

- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/environment.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/labextensions.txt
Adds the python packages and jupyterlab extension
> Adding ipyleaflet to base image

- docs/docs/step-by-step-walkthrough.md
Add installation with Conda to the step-by-step now that we have https://anaconda.org/conda-forge/qhub
> Update to include installation with conda

- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/apt.txt
Fixes https://github.com/Quansight/qhub/issues/147
> Add prerequisites

- .github/ISSUE_TEMPLATE/bug-report---.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation---.md
- .github/ISSUE_TEMPLATE/feature-request---.md
Adding basic info on bug report, feature request and docs issues.
> Update issue templates

- qhub/deploy.py
Currently we have a problem with parsing json on Github Actions, this replaces json parsing and uses regex matching for solving this problem.
> Fix json parsing issue by using regex instead

- .github/workflows/test.yaml
- qhub/cli/initialize.py
- qhub/initialize.py
- qhub/provider/cloud/digital_ocean.py
- tests/test_init.py
- tests/test_render.py
- tests/test_schema.py
Remove dependency of command line tool for small needed features from digital ocean rest api.
> Adding digital ocean methods without requiring doctl command line tool

- RELEASE.md
Add REALEASE.md document with descriptions.
> add release template description

- qhub/deploy.py
This makes the AWS deployment free of manual intervention.
> Auto add CNAME for AWS to Cloudflare

- README.md
Added the Code of Conduct to the README.md as required by Tania and Dharhas.
The next step is to write an inclusivity document, such as the one on [Kubleflow](https://github.com/kubeflow/community/blob/master/INCLUSIVITY.md) to help with our community standards for the get-go.
Addresses part of #277.
> include coc link on readme.md

- RELEASE.md
move the newer version-description of each release to the top of the file.
> reformat RELEASE.md

- setup.py
> Fixup for setup.py flake8 errors

- .github/workflows/image-pr.yaml
- .github/workflows/image.yaml
- .gitignore
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/environment.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/labextensions.txt
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/postBuild
There is an open issue for the transition to 3.X.X https://github.com/Quansight/qhub-cloud/issues/350
Closes https://github.com/Quansight/qhub-cloud/issues/350
> Pin jupyterlab version to >= 3.0.0

- RELEASE.md
- docs/conf.py
- docs/source/06_developers_contrib_guide/04_local_development.md
- qhub/template/{{ cookiecutter.repo_directory }}/image/Dockerfile.jupyterhub
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterhub/environment.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterhub/postBuild
Closes https://github.com/Quansight/qhub-cloud/issues/343
Also needed for work to address https://github.com/Quansight/qhub-cloud/issues/175.
> Jupyterhub docker image

- RELEASE.md
- docs/source/02_get_started/04_configuration.md
- qhub/cli/deploy.py
- qhub/initialize.py
- qhub/provider/cicd/github.py
- qhub/template/cookiecutter.json
- qhub/template/{{ cookiecutter.repo_directory }}/templates/jupyterhub_config.py.j2
- setup.py
- tests/assets/config_do_additional_node_groups.yaml
- tests/assets/config_do_auth0_provision.yaml
- tests/assets/config_gcp_gpu.yaml
Closes #175 
This PR allow for flexible end user customization of the jupyterhub theme.
> Jupyterhub theming using qhub-jupyterhub-theme

- docs/source/06_developers_contrib_guide/04_local_development.md
> Add information about Terraform version and k9s tool for debugging

- docs/source/02_get_started/01_installation.md
- docs/source/02_get_started/03_usage.md
Add @costrouc suggestions on issue #348.
Fixes #348.
> update instructions Terraform install

- .github/workflows/test.yaml
- docs/source/06_developers_contrib_guide/04_local_development.md
- tests/scripts/minikube-loadbalancer-ip.py
- tests/scripts/minikube-loadbalancer-ip.sh
Resolves https://github.com/Quansight/qhub-cloud/issues/361
> Setting correct load-balancer ip in local testing

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/aws.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
To be merged with PR
https://github.com/Quansight/qhub-terraform-modules/pull/43.
> Remove dependency hack prior to Terraform 0.13 release

- RELEASE.md
- docs/source/02_get_started/02_setup.md
- docs/source/02_get_started/04_configuration.md
- qhub/initialize.py
- qhub/schema.py
- qhub/template/cookiecutter.json
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/locals.tf
- tests/test_init.py
- tests/test_render.py
- tests/test_schema.py
Closes https://github.com/Quansight/qhub-cloud/issues/431
> Adding ability to specify node selector label for general, user, and worker

- RELEASE.md
- docs/source/02_get_started/04_configuration.md
- qhub/cli/initialize.py
- qhub/initialize.py
- qhub/schema.py
- qhub/template/cookiecutter.json
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/azure.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/state.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/variables.tf
- qhub/template/{{ cookiecutter.repo_directory }}/terraform-state/main.tf
- tests/test_init.py
- tests/test_render.py
- tests/test_schema.py
Closes https://github.com/Quansight/qhub-cloud/issues/432
> Support for namespaces with qhub deployments on kubernetes clusters

- qhub/deploy.py
- qhub/initialize.py
In the future this will help with automated testing of the qhub cluster.
Closes https://github.com/Quansight/qhub-cloud/issues/445
> Write default password to filesystem for qhub initialization

- .github/workflows/test.yaml
- docs/source/02_get_started/04_configuration.md
- qhub/cli/initialize.py
- qhub/deploy.py
- qhub/destroy.py
- qhub/initialize.py
- qhub/schema.py
- qhub/template/cookiecutter.json
- qhub/template/hooks/post_gen_project.py
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/state.tf
Closes https://github.com/Quansight/qhub-cloud/issues/449
> Initial work on using existing terraform backend and enable local backend to use kubernetes for storage

- docs/source/02_get_started/04_configuration.md
- qhub/schema.py
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/jupyterhub.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/templates/jupyterhub_config.py.j2
Closes https://github.com/Quansight/qhub-cloud/issues/450
> Support for flexible forms of authentication we need support for generic oauth

- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/environment.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterlab/postBuild
> VS code integration as part of the default deployment 

- .github/workflows/test.yaml
- docs/source/02_get_started/04_configuration.md
- docs/source/04_how_to_guides/1_qhub-aws-deploy_guide.md
- docs/source/04_how_to_guides/2_qhub-gcp-deploy_guide.md
- docs/source/04_how_to_guides/3_qhub-do-deploy_guide.md
- docs/source/05_reference/02_system_maintenance.md
- qhub/deploy.py
- qhub/initialize.py
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/versions.tf
Closes https://github.com/Quansight/qhub-cloud/issues/358
> Remove dask gateway helm chart

- .github/workflows/test.yaml
- tests_e2e/cypress.json
- tests_e2e/cypress/integration/main.js
- tests_e2e/cypress/plugins/index.js
- tests_e2e/cypress/support/index.js
- tests_e2e/package-lock.json
- tests_e2e/package.json
Cypress tests in tests.yaml workflow for Minikube. Tests login only.
> Cypress full tests from main

- docs/source/02_get_started/04_configuration.md
- qhub/cli/initialize.py
- qhub/initialize.py
- qhub/schema.py
- qhub/template/cookiecutter.json
- qhub/template/hooks/post_gen_project.py
- qhub/template/{{ cookiecutter.repo_directory }}/.gitlab-ci.yml
> Gitlab CI added and making CI Optional

- .github/workflows/test.yaml
- RELEASE.md
- qhub/cli/deploy.py
- qhub/cli/destroy.py
- qhub/cli/initialize.py
- qhub/cli/render.py
- qhub/cli/validate.py
- qhub/render/__init__.py
- qhub/render/jinja.py
- qhub/template/hooks/post_gen_project.py
- setup.py
- tests/test_render.py
> Changing from pyyaml -> ruamel.yaml to ensure no duplicate keys

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/azure.tf
- Pins k8s version for azure deployment
- renames node resource group to enable multiple qhub deployments per azure account
> Node group fix and Pin k8s for azure

- .github/workflows/image.yaml
- .github/workflows/release.yaml
- qhub/render/__init__.py
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/jupyterhub-pr.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/jupyterhub.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/qhub-ops.yaml
Github workflow only needs deploy now, no separate terraform workflows
Closes #556
> Github Worfkflow templates simplified

- .github/workflows/stale_bot.yml
> Auto close issues with stale bot

- docs/source/02_get_started/02_setup.md
- docs/source/02_get_started/03_usage.md
- docs/source/02_get_started/04_configuration.md
- docs/source/03_tutorials_and_samples/1_project_setup_tutorial.md
The PR #486 from Lais was set to merge into dev branch, which we no longer used.
Basically, this PR contains the same content rebased to main, but the original PR messed up so here is a new one.
> Azure docs from PR #486

- README.md
Fix typos, add Azure to the list of supported Cloud providers, correct wording and update links.
> fix links and update README.md

- docs/index.md
- docs/source/03_tutorials_and_samples/01_cloud_setup.md
- docs/source/03_tutorials_and_samples/02_qhub_pangeo.md
- docs/source/04_how_to_guides/6_preemptible_instance_with_qhub.md
- docs/source/04_how_to_guides/8_login_qhub_training.md
remove blank tutorial pages too
> Just made clear that training is a Quansight thing

- docs/index.md
- docs/source/02_get_started/09_end_user_faq.md
Currently in the form of Q&A to get something written up quickly.
Confirmed that it builds and looks reasonable. Not sure about the location though.
> first pass at end user docs

- .github/workflows/test.yaml
- docs/source/06_developers_contrib_guide/04_tests.md
- tests_e2e/cypress/.gitignore
- tests_e2e/cypress/integration/main.js
Docs for running Cypress locally.
Run tests.yaml workflow on every branch.
> Cypress tests - simplify for Minikube

- docs/source/06_developers_contrib_guide/04_tests.md
Assimilate the command docker will prompt user to make into the useradd to docker step.
Alternative is for user to logout/in/reboot.
> Instruct user to activate docker group addition.

- qhub/schema.py
- qhub/template/cookiecutter.json
- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/qhub-ops.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/prefect/chart/templates/prefect.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/prefect/chart/values.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/prefect/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/prefect/variables.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/variables.tf
Fixes #655 #662 
Documentation PR:  #641
> Prefect Integration fixes

- docs/source/08_integrations/1_prefect.md
Fixes #404 #661 
The fix for prefect issues is here: #667
> Add documentation for Prefect Integration

- docs/source/08_integrations/2_clearml.md
> fix clearml deploy docs

- docs/source/06_developers_contrib_guide/04_tests.md
Tweaks to local deployment docs regarding metallb for clarity
> update docs regarding metallb for local deployment

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/aws.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/aws/accounting/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/aws/accounting/variables.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/aws/kubernetes/policy.tf
- qhub/template/{{ cookiecutter.repo_directory }}/terraform-state/main.tf
Extra tags added to AWS resources so they can be found and destroyed more easily.
> More AWS Tags

- qhub/deploy.py
> Add ClearML DNS only when its enabled

- .github/workflows/test.yaml
- docs/source/06_developers_contrib_guide/06_release.md
In addition to documentation on releases. Tests are disabled for only doc changes.
> Adding pre-release checklist to release notes

- qhub/template/{{ cookiecutter.repo_directory }}/.gitlab-ci.yml
> allow branch installation when using gitlab deployment

- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/versions.tf
> Fix connectivity issues with AWS EKS via Terraform

- .github/workflows/test.yaml
Fixes #747 
See this https://github.com/Quansight/qhub/issues/747#issuecomment-891673376
> Fix workflow syntax to run tests

- docs/source/admin_guide/faq.md
> Add docs for autoscaler bug

- docs/source/dev_guide/testing.md
- Adds a note to minikube local testing
- Makes some sections of the local testing docs collapsible for extra style points
@costrouc this one is actually ready to review :)
> update docs for local testing with slow internet

- qhub/template/{{ cookiecutter.repo_directory }}/image/Dockerfile.dask-worker
- qhub/template/{{ cookiecutter.repo_directory }}/image/Dockerfile.jupyterhub
- qhub/template/{{ cookiecutter.repo_directory }}/image/Dockerfile.jupyterlab
Work in progress change of Docker image bases to ubuntu:20.04
> Rebase Docker images to ubuntu:20.04  - WIP

- .github/workflows/kubernetes_test.yaml
- qhub/cli/__init__.py
- qhub/cli/keycloak.py
- qhub/keycloak.py
- setup.py
`keycloak adduser username [password]` command, used for adding example-user to the Cypress minikube tests.
> K8s tests - keycloak adduser

- .github/PULL_REQUEST_TEMPLATE.md
> DOCS: Add a PR Template

- .github/workflows/image.yaml
Fixes | Closes | Resolves #911 
-
> Mirror docker images to ghcr and quay container registry

- qhub/template/{{ cookiecutter.repo_directory }}/image/scripts/install-conda-environment.sh
- qhub/template/{{ cookiecutter.repo_directory }}/image/scripts/install-conda.sh
- This PR will add mamba to the QHub docker images, which will speed up the image build times considerably 
- To reduce the complexity of #904, I will be breaking it up into smaller PRs
> Create and solve envs using mamba

- qhub/render/__init__.py
- qhub/schema.py
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/extensions.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/qhubextension/main.tf
- qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/qhubextension/variables.tf
Closes #902 
Adds qhub-config-yaml secret containing a copy of the YAML file. Also mounts it on extension pods (optionally)
- [x ] New feature (non-breaking change which adds a feature)
- [x ] No
> qhub-config.yaml as a secret

- qhub/template/{{ cookiecutter.repo_directory }}/.github/workflows/qhub-ops.yaml
Fix for integration-tests, getting github-actions CI to work.
- template fix
> cookicutter template out of raw

- qhub/template/{{ cookiecutter.repo_directory }}/image/jupyterhub/environment.yaml
- qhub/template/{{ cookiecutter.repo_directory }}/templates/jupyterhub_config.py.j2
- uses qhub-jupyterhub-theme==0.3.3
- simplified jupyterhub config
This simplifies the code and also makes it more extensible.
> use qhub-jupyterhub-theme 0.3.3 to simplify JupyterHub config

- docs/source/installation/setup.md
Clarifies some commands for configuring auth0
> minor updates to keycloak docs

- docs/source/installation/setup.md
> DOCS: Fix broken link in setup doc

- qhub/deploy.py
- qhub/render/__init__.py
Fixes #1033 
- Add a condition to deploy `01-terraform-state` stage, only when "remote" state is applied (cloud deployment)
> Add remote state condition for 01-terraform-state provisioning

- qhub/destroy.py
Fixes #1050 
- Add conditional to destroy `01-terraform-state` stage
> Destroy terraform-state stage when condition match

- qhub/deploy.py
- qhub/destroy.py
See the docs on keycloak.md that specify how this can be done.
> Adding ability to specify overrides back into keycloak configuration

- .github/workflows/docs.yml
- .github/workflows/image.yaml
- .github/workflows/kubernetes_test.yaml
- .github/workflows/test-provider.yaml
- .github/workflows/test.yaml
Fixes #1060
- Removes concurrency group
- Removes cancel-in-progress
> FIX: Remove concurrency groups

- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/03-profiles.py
> Ensure that the shared folder symlink only exists if user has shared folders

- qhub/template/image/Dockerfile.dask-worker
- qhub/template/image/Dockerfile.jupyterhub
- qhub/template/image/Dockerfile.jupyterlab
Continuation of #1072. Some of the git commit history became confusing so this is to start fresh off of the latest main commit.
> remove jovyan user

- .github/workflows/kubernetes_test.yaml
- .github/workflows/test-provider.yaml
- .github/workflows/test.yaml
> Use paths instead of paths-ignore so that test only run on changes to given paths

- qhub/destroy.py
- qhub/provider/terraform.py
> Relax qhub destroy to attempt to continue destroying resources

- qhub/destroy.py
Closes #1115
`qhub destory --config qhub-config.yaml` will now print about the success/failure of stages to delete.
> Adding status field to each destroy stage to print status

- qhub/initialize.py
- qhub/schema.py
- qhub/stages/input_vars.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/variables.tf
- qhub/upgrade.py
> FIX: Remove Conda Store from default images

- .github/workflows/kubernetes_test.yaml
- qhub/template/image/scripts/install-conda.sh
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/03-profiles.py
> [BUG] Removing jovyan home directory and issue with nss confiuration

- docs/source/user_guide/code_server.md
- docs/source/user_guide/dashboard.md
- docs/source/user_guide/dask_gateway.md
- docs/source/user_guide/environments.md
- docs/source/user_guide/faq.md
- docs/source/user_guide/getting_started.md
- docs/source/user_guide/ssh.md
- docs/source/user_guide/training.md
- Updates the User Guide docs to fix typos and some awkward language
> Fix typos in user guide docs

- docs/source/admin_guide/index.md
- docs/source/dev_guide/release.md
- docs/source/installation/configuration.md
- docs/source/user_guide/index.md
- pyproject.toml
- qhub/provider/cicd/github.py
- qhub/provider/cicd/gitlab.py
Related to #1009 
- Update configuration docs to reflect recent changes
- Add newly created docs to toctree
> Minor docs clean up for v0.4.0 release

- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/config/conda_store_config.py
Related to quansight/conda-store#262
> Fixing concurrency not being specified in configuration

- qhub/provider/terraform.py
> Allow terraform init to upgrade providers within version specification

- setup.cfg
> Adding missing __init__ files

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- docs/ext/substitute.py
- environment-dev.yaml
- qhub/render.py
- qhub/stages/checks.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/config/conda_store_config.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_plotly.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_streamlit.py
- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
- setup.cfg
- tests/scripts/minikube-loadbalancer-ip.py
- tests/test_render.py
- tests_deployment/test_jupyterhub_ssh.py
Fixes | Closes | Resolves #1204 
- Add a means of rendering the `.gitignore` file to avoid committing terraform provider related files. 
> Render `.gitignore`, black py files

- qhub/initialize.py
- qhub/utils.py
Fixes | Closes | Resolves #1212
- Update qhub-dask from `0.3.13` to `0.4.0`
CI should be sufficient.
> Update qhub-dask pinned version

- docs/source/dev_guide/testing.md
- qhub/utils.py
- tests/test_links.py
Fixes | Closes | Resolves #1215 
- Fix env doc links and tests
Added a unit test
> Fix env doc links and add corresponding tests

- qhub/initialize.py
- qhub/template/image/jupyterhub/environment.yaml
- qhub/template/image/jupyterlab/environment.yaml
Fixes | Closes | Resolves #1232 
- Update cdsdashboards in hub and lab images
- Update voila (and cdsdashboards) in default conda environment
> Update cdsdashboards to 0.6.1, Voila to 0.3.5

- qhub/stages/checks.py
- qhub/template/stages/07-kubernetes-services/outputs.tf
Resolves https://github.com/Quansight/qhub/issues/1223
- fix output check bug
> output check fix

- docs/source/installation/existing.md
- qhub/initialize.py
Fixes | Closes | Resolves #1229 
- Bump `panel==0.12.4` to `0.12.7`
> Update panel version to fix jinja2 recent issue

- .github/workflows/test-release.yaml
- Add workflow to that will publish a QHub release on Test PyPI
This is the test.
> Add test-release workflow

- docs/source/installation/configuration.md
- qhub/template/stages/02-infrastructure/azure/main.tf
- qhub/template/stages/02-infrastructure/azure/variables.tf
- qhub/template/stages/02-infrastructure/gcp/main.tf
- qhub/template/stages/02-infrastructure/gcp/modules/kubernetes/main.tf
- qhub/template/stages/02-infrastructure/gcp/modules/kubernetes/variables.tf
- qhub/template/stages/02-infrastructure/gcp/variables.tf
Fixes | Closes | Resolves #1211 
- Defines terraform override variables to able to deploy in VPC for GCP.
> [WIP] Add support for VPC deployment for GCP via terraform overrides

- docs/source/installation/configuration.md
- docs/source/user_guide/faq.md
Fixes | Closes | Resolves #1124 
- Add an FAQ on the possibility of an inplace  upgrade to the `general` node instance type.
> Add docs for general node upgrade

- docs/source/dev_guide/minikube.md
- docs/source/user_guide/environments.md
Fixes | Closes | Resolves #908 #1034 
- Two minor doc updates before v0.4.1 release.
> Minor doc updates

- RELEASE.md
> Release notes for `v0.4.1`

- environment-dev.yaml
- setup.cfg
At the moment qhub init doesn't works with cloud initializations:
```python
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.8.13/x64/bin/qhub", line 5, in <module>
from qhub.__main__ import main
File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/qhub/__main__.py", line 3, in <module>
from qhub.cli import cli
File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/qhub/cli/__init__.py", line 7, in <module>
from qhub.cli.cost import create_cost_subcommand
File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/qhub/cli/cost.py", line 3, in <module>
from qhub.cost import infracost_report
File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/qhub/cost.py", line 7, in …
```
> Fix missing import: `rich` : broken qhub init with cloud

- qhub/provider/terraform.py
Fixes | Closes | Resolves #1367 
- Add support for downloading terraform binary for M1 Macbook
> Add support for terraform binary download for M1

- .cirun.yml
- .github/workflows/kubernetes_test.yaml
- Updates Cirun's config to use labels instead of workflow file path, this is a recent change to Cirun's API. `workflow` file path is deprecated.
> Update Cirun.io config to use labels

- .github/workflows/release.yaml
> Minor update to release workflow

- .github/workflows/release.yaml
> Clean up release workflow

- RELEASE.md
> Add release notes for v0.4.4

- .github/ISSUE_TEMPLATE/release-checklist.md
- .github/ISSUE_TEMPLATE/testing-checklist.md
Fixes | Closes | Resolves #1384 
-
> Update release, testing checklist

- qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/worker.tf
- Ensure that the conda-store worker pod restarts whenever a new conda environment is added to the `qhub-config.yaml`.
> Restart conda-store worker when new conda env is added to config.yaml

- qhub/cli/main.py
- qhub/render.py
> Add deploy flags and change repository default value

- qhub/cli/_init.py
- qhub/cli/main.py
> Remove `dotenv` work.

- qhub/template/stages/01-terraform-state/azure/main.tf
- qhub/template/stages/02-infrastructure/azure/versions.tf
Resolves #1430
- Bump the version of the [AzureRM Terraform Provider](https://github.com/hashicorp/terraform-provider-azurerm)
Updating to 3.22 rather than the [latest](https://github.com/hashicorp/terraform-provider-azurerm/tags) because this is the version I have been using for the last couple of weeks. I don't think this would require any new tests, but I'm not certain. I would guess that the tests you already have in place will likely cover this.
> Update azurerm version

- qhub/cli/main.py
> Add `version` options to Nebari CLI

- .github/workflows/kubernetes_test.yaml
- .github/workflows/test-provider.yaml
- qhub/cli/_init.py
- qhub/cli/_keycloak.py
- qhub/cli/main.py
- qhub/schema.py
- tests_deployment/constants.py
- tests_deployment/test_dask_gateway.py
- tests_deployment/test_jupyterhub_ssh.py
- tests_deployment/utils.py
- tests_e2e/cypress/integration/main.js
- tests_e2e/cypress/plugins/index.js
- Update CI to use the new Nebari, typer based CLI. 
> Update CI to use new nebari cli entrypoint

- .github/workflows/kubernetes_test.yaml
- .github/workflows/run-pre-commit.yaml
- .github/workflows/test-provider.yaml
- .github/workflows/test.yaml
- pyproject.toml
Closes #1454 
Closes https://github.com/Quansight/qhub/issues/1395
- Update CI to run on `release/**` branches
- Switch project from SemVer to CalVer
> Switch to CalVer

- README.md
- Updates readme logo reference
> Update README logo reference

- README.md
- cherry-pick Update README logo (#1514)
> cherry-pick Update README logo (#1514)

- nebari/cli/init.py
- nebari/cli/main.py
Closes #1525 
Closes #1530
- Fixes bug reported in #1525
- Fixes GitOps linter action in #1530 
> Small CLI fixes

- .github/ISSUE_TEMPLATE/testing-checklist.md
- .github/workflows/kubernetes_test.yaml
- .github/workflows/run-pre-commit.yaml
- .github/workflows/test-provider.yaml
- .github/workflows/test.yaml
> Run CI on develop branch

- .github/workflows/kubernetes_test.yaml
The `kubernetes_test` CI is failing because we are using a deprecated version of `node.js`. This PR simply updates this version.
> Update `setup-node` version

- .github/workflows/infracost.yml
- .github/workflows/kubernetes_test.yaml
- .github/workflows/test-provider.yaml
> Fix skip check for workflows

- RELEASE.md
> Add release notes for 2022.11.1

- nebari/cli/init.py
- nebari/cli/main.py
- nebari/schema.py
> Add check_repository_cred function to CLI

- nebari/stages/input_vars.py
- nebari/template/stages/03-kubernetes-initialize/versions.tf
- nebari/template/stages/04-kubernetes-ingress/variables.tf
- nebari/template/stages/04-kubernetes-ingress/versions.tf
- nebari/template/stages/05-kubernetes-keycloak/versions.tf
- nebari/template/stages/06-kubernetes-keycloak-configuration/versions.tf
- nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/argo-workflows/versions.tf
- nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/kbatch/versions.tf
- nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/monitoring/versions.tf
- nebari/template/stages/07-kubernetes-services/versions.tf
- nebari/template/stages/08-nebari-tf-extensions/versions.tf
Two changes:
- For deployments that wish to use an `existing` TLS certificates, ensure that the `secret_name` from the `nebari-config.yaml` is passed to the Terraform scripts. 
- Fixes #1581
- Update the Kubernetes terraform provider to `2.16.1`.
- In  1.24+, Kubernetes does not generate a token for a service account by default ([Kubernetes release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes) + [fix in the kubernetes terraform provider](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1792)).
> Pass `secret_name` to TF scripts when certificate type = exisiting

- nebari/stages/input_vars.py
Closes https://github.com/nebari-dev/nebari/issues/1739
> Typo in the conda-store <-> conda_store key

- .github/release-notes-sync-config.yaml
ref: https://github.com/nebari-dev/nebari-docs/pull/318
> Update path in release-notes-sync action

- .github/workflows/release.yaml
- .github/workflows/test-provider.yaml
Update vault url since it recently changed
> Update vault url

- .github/workflows/contributor.yaml
Fixing my own mistake from #1766.
> fix copy-paste error

- .github/workflows/contributor.yaml
> add instructions insufficient permissions of contributor trigger

- .cirun.yml
This is to transfer Cirun from old AWS account to `nebari-dev-ci`.
> Update AMI  in `.cirun.yml` for nebari-dev-ci AWS account

- pytest.ini
Implements https://github.com/nebari-dev/nebari/pull/1700#discussion_r1160669973 after https://github.com/nebari-dev/nebari/pull/1700#issuecomment-1531564494.
> turn warnings into errors with pytest

- .github/workflows/kubernetes_test.yaml
- .github/workflows/test-provider.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
We no longer use `setuptools` since #1545, but `setup.cfg` is still mentioned in several places inside the repository. This PR fixes that.
> purge setup.cfg

- .github/workflows/test-provider.yaml
- .github/workflows/test.yaml
Fixes accidental indentation from #1804 
> Dedent fail-fast

- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/argo-workflows.tf
- src/_nebari/stages/kubernetes_services/template/clearml.tf
- src/_nebari/stages/kubernetes_services/template/conda-store.tf
- src/_nebari/stages/kubernetes_services/template/dask_gateway.tf
- src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
- src/_nebari/stages/kubernetes_services/template/monitoring.tf
- src/_nebari/stages/kubernetes_services/template/variables.tf
- src/nebari/schema.py
Continue to add schema for InputVars. In this PR, I split out the input vars for each of the services into it's own schema in preparation for creating a stage/plugin for each of the different services. 
> Add InputVar schema to kubernetes_services stage

- src/_nebari/template/stages/02-infrastructure/aws/main.tf
- src/_nebari/template/stages/02-infrastructure/aws/modules/kubernetes/locals.tf
- src/_nebari/template/stages/02-infrastructure/aws/modules/kubernetes/variables.tf
> AWS gov cloud support

- src/_nebari/upgrade.py
Update the `nebari upgrade` command so that users upgrading from a previous version of Nebari update their nebari-config.yaml to the latest `2023.7.2` release (skipping the `2023.7.1`) altogether.
Related to #1885 
> Update upgrade command for 2023.7.2

- src/_nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_server_config.py.tpl
> enabling viewing hidden files in jupyterlab file explorer

- src/_nebari/provider/cloud/amazon_web_services.py
> paginator for boto3 ec2 instance types

- README.md
> Update README.md -- fix typo.

- .gitignore
- src/_nebari/config.py
- src/_nebari/initialize.py
- src/_nebari/provider/cloud/amazon_web_services.py
- src/_nebari/provider/cloud/digital_ocean.py
- src/_nebari/stages/terraform_state/template/do/modules/terraform-state/versions.tf
- src/_nebari/utils.py
- tests/tests_integration/deployment_fixtures.py
- tests/tests_unit/test_config.py
> Add more unit tests, add cleanup step for Digital Ocean integration test

- pytest.ini
- src/_nebari/subcommands/init.py
- tests/tests_unit/test_cli_init.py
> nebari init unit tests

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
> Bug fix - JH singleuser environment getting overwritten

- src/nebari/plugins.py
> TYP: fix typing error in plugins

- src/_nebari/provider/cloud/azure_cloud.py
- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/stages/infrastructure/template/azure/main.tf
- src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/main.tf
- src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/variables.tf
- src/_nebari/stages/infrastructure/template/azure/modules/registry/main.tf
- src/_nebari/stages/infrastructure/template/azure/modules/registry/variables.tf
- src/_nebari/stages/infrastructure/template/azure/variables.tf
- src/_nebari/stages/terraform_state/__init__.py
- src/_nebari/stages/terraform_state/template/azure/main.tf
- src/_nebari/stages/terraform_state/template/azure/modules/terraform-state/main.tf
- src/_nebari/stages/terraform_state/template/azure/modules/terraform-state/variables.tf
- tests/tests_unit/cli_validate/azure.happy.yaml
> Allow users to specify Azure tags

- pytest.ini
- src/_nebari/subcommands/deploy.py
- tests/tests_unit/conftest.py
- tests/tests_unit/test_cli_deploy.py
Related doc changes: https://github.com/nebari-dev/nebari-docs/pull/358
> CLI: handle removed dns options in deploy command

- src/_nebari/upgrade.py
> 2023.9.1 AWS upgrade changes

- src/_nebari/subcommands/init.py
> fix typo in guided init for Digital Ocean

- README.md
- pyproject.toml
> DEPS: sync supported python version

- .github/workflows/test.yaml
- pyproject.toml
Python 3.12 is the new kid in the town
> Test support for Python 3.12

- src/_nebari/upgrade.py
In preparation for the 2023.11.1 release.
> Add upgrade command for 2023.11.1

- RELEASE.md
> Update release notes for 2023.11.1

- .github/ISSUE_TEMPLATE/release-checklist.md
- src/_nebari/constants.py
> update constants.py with current version

- src/_nebari/upgrade.py
Closes #2137
Part of #2157 
Add's upgrade command for 2023.12.1
> add 2023.12.1 upgrade command

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/dask-gateway/files/gateway_config.py
> Add cdn as environment variable for bokeh resources.

- src/_nebari/stages/kubernetes_keycloak/template/modules/kubernetes/keycloak-helm/values.yaml
> Update busybox image tag version (#2167)

- src/_nebari/constants.py
> update release version

- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/configmaps.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_jupyterlab_pioneer_config.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_jupyterlab_pioneer_config.py.tpl
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
- src/_nebari/stages/kubernetes_services/template/variables.tf
- Documentation PR: https://github.com/nebari-dev/nebari-docs/pull/384
- Docs preview: https://deploy-preview-384--nebari-docs.netlify.app/docs/how-tos/telemetry
- Conda Forge release: https://github.com/conda-forge/staged-recipes/pull/24685
- JupyterLab 4.x upgrade + jupyterlab-pioneer: https://github.com/nebari-dev/nebari-docker-images/pull/101
> Add jupyterlab-pioneer

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
This now shows as default App
Relevant: https://github.com/nebari-dev/jhub-apps/pull/63
See Comment: https://github.com/nebari-dev/jhub-apps/issues/51#issuecomment-1883561664
> Remove JupyterLab from services list

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterlab/overrides.json
> Add Nebari menu item configuration.

- RELEASE.md
> update release notes

- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/configmaps.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_server_config.py.tpl
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
> Expose jupyter's preferred dir as a config option

- src/_nebari/upgrade.py
> add upgrade step

- .github/workflows/generate_cli_doc.yml
- .github/workflows/release.yaml
- .github/workflows/run-precommit.yaml
- .github/workflows/test-provider.yaml
- .github/workflows/test.yaml
- .github/workflows/test_aws_integration.yaml
- .github/workflows/test_conda_build.yaml
- .github/workflows/test_do_integration.yaml
- .github/workflows/test_gcp_integration.yaml
- .github/workflows/test_helm_charts.yaml
- .github/workflows/test_local_integration.yaml
- .github/workflows/typing.yaml
> Upgrade Actions versions

- src/_nebari/render.py
- src/_nebari/utils.py
We recently upgraded the min supported python version for Nebari to 3.10 so I'm removing a deprecated code path in this PR.
> remove depracated code paths

- src/_nebari/upgrade.py
> New upgrade step for 2024.3.3

- tests/tests_unit/qhub-config-yaml-files-for-upgrade/qhub-config-do-310-customauth.yaml
- tests/tests_unit/qhub-config-yaml-files-for-upgrade/qhub-config-do-310.yaml
remove references to deprecated cdsdashboards
> remove references to deprecated cdsdashboards

- src/_nebari/config.py
- src/_nebari/initialize.py
- src/_nebari/stages/infrastructure/__init__.py
The average user doesn't know what options they have available to them to adjust.  Those who deploy fresh deployments may run into the situation where they need to adjust these immediately, and it's not apparent how to do so (https://github.com/nebari-dev/nebari/issues/2122), and there aren't docs on how to do so.  There is a more [comprehensive PR](https://github.com/nebari-dev/nebari/pull/2294) in progress, but in the mean time, this adds node groups to the nebari config which was the source of the issue cited above.  I don't see this as a final solution, but as an easy workaround for the time being.
> add default node groups to config

- .github/workflows/test_local_integration.yaml
> Update concurrency settings for Integration tests

- RELEASE.md
- src/_nebari/constants.py
- src/_nebari/initialize.py
- src/_nebari/stages/infrastructure/__init__.py
- src/_nebari/upgrade.py
> Prepare 2024.4.1 release

- RELEASE.md
> Update release date and add two new PRs to the whats changed section.

- pyproject.toml
> Update `python-keycloak` version pins constraints

- RELEASE.md
- src/_nebari/constants.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- src/_nebari/upgrade.py
- Add nebari 2024.5.1 upgrade
- Add release notes
- Rollback Jupyterhub v5 update, untill next release
> Release 2024.5.1 updates

- tests/tests_e2e/cypress/integration/main.js
> Update selector for Start server button to use button tag

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
Due to an issue with the latest release cycle, the changes made from PR #2427 were rolled back to complete the release; this PR re-introduces these changes.
This merely restores the work originally created by the authors mentioned in the PR, to whom all credit is due.
> Restore JupyterHub updates from PR-2427

- tests/tests_deployment/utils.py
Fixes the deployment test issue seen https://github.com/nebari-dev/nebari/pull/2475.
I was able to track this down to our version of requests changed from 2.31.0 to 2.32.2 recently which contains a fix for a bug that was making our tests pass previously ([psf/requests@main/HISTORY.md#2320-2024-05-20](https://github.com/psf/requests/blob/main/HISTORY.md?rgh-link-date=2024-05-23T04%3A48%3A59Z#2320-2024-05-20)).
> add verify=false since we use self signed cert in tests

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- Follow up to https://github.com/nebari-dev/nebari/pull/2427
- https://github.com/nebari-dev/nebari/pull/2468
- Sibling to https://github.com/nebari-dev/nebari-docker-images/pull/145 (may need to be merged and pre-released first)
- Changelog: https://github.com/jupyterhub/jupyterhub/compare/5.0.0b1...5.0.0b2
For reference the helm chart - JupyterHub version mapping is available at https://hub.jupyter.org/helm-chart/
> Upgrade to JupyterHub 5.0.0b2

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- Follow up to https://github.com/nebari-dev/nebari/pull/2468
- https://github.com/nebari-dev/nebari/pull/2468
- Sibling to https://github.com/nebari-dev/nebari-docker-images/pull/149 (may need a merge & pre-released first)
- Changelog: https://github.com/jupyterhub/jupyterhub/compare/5.0.0b2...5.0.0
For reference the helm chart - JupyterHub version mapping is available at https://hub.jupyter.org/helm-chart/
> Use Helm Chart for JupyterHub 5.0.0 final

- .github/workflows/test_azure_integration.yaml
> don't run azure deployment on PRs, only on schedule and manual trigger

- src/_nebari/upgrade.py
Adds note that users may need to redeploy due to timeout if switching out nodes.
> upgrade note

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/monitoring/dashboards/Main/conda_store.json
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/monitoring/dashboards/Main/traefik.json
Closes https://github.com/nebari-dev/nebari/issues/2504
To test this PR:
1. Deploy Nebari from [this branch](https://github.com/nebari-dev/nebari/tree/fix-conda-store-dashboard)
2. Create a new user in Keycloak and make sure to specify its email address (otherwise Grafana will complain)
3. Log-in with the newly created user
4. Navigate to `/monitoring`
5. On the left panel, open Dashboards and then on the main panel open the Main folder.
6. Navigate to:
* a. Conda-Store
* b. Traefik
You should see the dashboards working:
> Fix conda-store and Traefik Grafana Dashboards

- src/_nebari/upgrade.py
- tests/tests_unit/test_upgrade.py
Closes https://github.com/nebari-dev/nebari/issues/2533
- [ x] New feature (non-breaking change which adds a feature)
To test this PR:
1. Install `nebari==2025.5.1`
2. Run `nebari deploy`
3. Install nebari in development mode from [this branch](https://github.com/nebari-dev/nebari/tree/upgrade-on-users-behalf)
4. Run `nebari upgrade`
5. Follow the prompt and allow Nebari to run the `kubectl` commands on your behalf
6. Run `nebari deploy`
> Add option to run CRDs updates and DaemonSet deletion on user's behalf.

- RELEASE.md
- src/_nebari/constants.py
> Prepare 2024.6.1 release

- src/_nebari/stages/infrastructure/template/aws/modules/s3/main.tf
- src/_nebari/stages/terraform_state/template/aws/modules/terraform-state/main.tf
> restrict public access and add bucket encryption using cmk

- src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/main.tf
> add overwrite to AWS coredns addon

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/skel/.bashrc
Fixes https://github.com/nebari-dev/nebari/issues/2571
> add note about ~/.bash_profile

- src/_nebari/stages/kubernetes_services/__init__.py
- src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
- Accompanies https://github.com/nebari-dev/jupyterlab-gallery/pull/35
- Sibling to https://github.com/nebari-dev/nebari-docker-images/pull/170
> Expose jupyterlab-gallery branch and depth options

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub-ssh/variables.tf
Fixes #2566 
Upgrades Jupyterhub ssh to latest available image
N/A
> #2566 Upgrade Jupyterhub ssh image

- src/_nebari/upgrade.py
> Update upgrade command for 2024.7.1

- .github/workflows/test-provider.yaml
- .github/workflows/test_aws_integration.yaml
- .github/workflows/test_azure_integration.yaml
- .github/workflows/test_do_integration.yaml
- .github/workflows/test_gcp_integration.yaml
The current version we're using is over an year old.
> Upgrade Hashicorp Vault action

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
- Fixes https://github.com/nebari-dev/nebari/issues/2570
- Depends on https://github.com/nebari-dev/jhub-apps/pull/458
Nope
> Pass `oauth_no_confirm=True` to jhub-apps

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
- Sibling to https://github.com/nebari-dev/nebari-docker-images/pull/179
- Together with the above will close https://github.com/nebari-dev/nebari/issues/2602
:rocket:
> Use Helm Chart for JupyterHub 5.1.0

- .github/PULL_REQUEST_TEMPLATE.md
> Add a how to test section to PR template

- CONTRIBUTING.md
- README.md
- SECURITY.md
Hi folks, found a couple broken links while going through some of the getting started materials! I will add more as I find them or open a new PR if this is merged before I do.
> fix broken links in README.md, SECURITY.md, and CONTRIBUTING.md

- .github/ISSUE_TEMPLATE/release-checklist.md
Slight adjustment to release checklist language since we often don't announce a merge freeze.
> Release Process Checklist Updates

- src/_nebari/stages/kubernetes_services/template/rook-ceph.tf
I saw some old comments and wanted to clean them up a bit.
> remove comments

- src/_nebari/stages/kubernetes_services/template/rook-ceph.tf
https://github.com/nebari-dev/nebari/issues/2712
Fixes https://github.com/nebari-dev/nebari/issues/2712 - deploy the rook-ceph helm chart only as needed
- [ X  ] Bug fix (non-breaking change which fixes an issue)
> Deploy Rook Ceph Helm only when Ceph FS Needed

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
> fix group mounting paths

- tests/tests_unit/test_cli_validate.py
Fixes [#2783](https://github.com/nebari-dev/nebari/issues/2783)
> Fix Pytest Tests failing on PRs updating src

- RELEASE.md
Fixes https://github.com/nebari-dev/nebari/issues/2801
> add broken note

- RELEASE.md
Closes #2805 
Compare the changes against https://github.com/nebari-dev/nebari-docs/pull/526/commits/1815d2159cdb2028d260528416a814d996958912 and validate that all checks ran successfully there.
> Fix release notes formatting to restore docs syncing functionality

- src/_nebari/stages/infrastructure/template/aws/modules/network/main.tf
> Added security group rule descriptions

- tests/tests_unit/test_upgrade.py
> Update test_upgrade.py to skip upgrade prompt while testing

- .github/workflows/test_local_integration.yaml
> Bump timeout and max restarts for the await workloads action

- .github/workflows/test_aws_integration.yaml
This PR simply removes a typo that was unintended introduced and is causing our AWS integration tests to run with a log level of `TRACE` every time.
> Remove unintended character at the end of the TF_LOG variable

- src/_nebari/cli.py
- src/_nebari/subcommands/info.py
- adds info command text display
- change the order of command display
- Run locally 
- fix #2849 and also #2846 
- [ x] Other (please describe):
- [ x] Did you test the pull request locally?
> adds info command text display & change the order of command display

- .github/workflows/test_local_integration.yaml
> Update `fsnotify` max user watches/instances limits

- src/_nebari/upgrade.py
Part of #2986 
Adds upgrade step for 2025.3.1
> add upgrade step for 2025.3.1

- src/_nebari/stages/terraform_state/__init__.py
> update deprecated pydantic function

- src/_nebari/upgrade.py
fixes https://github.com/nebari-dev/nebari/issues/2824
related to https://github.com/nebari-dev/nebari/pull/2605
> add node taint upgrade step

- .github/PULL_REQUEST_TEMPLATE.md
> Include documentation requirement for new ENH under PR template

- tests/common/config_mod_utils.py
Fixes https://github.com/nebari-dev/nebari/issues/3026
Fixes AWS deployment test
Re-run AWS deployment test against this branch and see that it passes.  I've retriggered the AWS deployment test from this branch in [this github action](https://github.com/nebari-dev/nebari/actions/runs/14339538273).
> ensure default node group taints are used in deployment tests

- .github/workflows/trivy.yml
> Use ubuntu-latest instead of 20.04 in the Code Scanning (Trivy) GHA workflow

- .github/workflows/test_local_integration.yaml
> Run nebari destroy using conda in local integration tests

- tests/tests_unit/test_upgrade.py
Closes https://github.com/nebari-dev/nebari/issues/3040
Make sure the upgrade unit tests are passing.
You can either:
1. run the following command locally:
```bash
pytest tests/tests_unit/test_upgrade.py::test_upgrade_4_0
```
2. or, make sure that the tests in this PR are passing.
> Monkeypatch version validator to avoid failing tests

- pyproject.toml
Addresses https://github.com/advisories/GHSA-m5vv-6r4h-3vj9
Make sure Azure deployments work as expected. I've triggered our Azure deployment tests against this branch in https://github.com/nebari-dev/nebari/actions/runs/14624056960
> Upgrade azure-identity

- .cirun.yml
Cirun now supports runner monitoring for AWS runners. This would enable monitoring, for evaluating performance, CI failure postmortem, etc.
The monitoring link is available in the CI logs in the first step ("Setup Job")
The dashboard can be seen by clicking on the link, by logging in via cirun account:
Note: This does not uses any extra resources and has no cost implications, this is hosted on cirun's infra.
> Enable resource monitoring for cirun runners

- .github/workflows/trivy.yml
Closes #3046 
Check that dependencies are being scanned and vulnerabilities found are reported. You can see them on https://github.com/nebari-dev/nebari/security/code-scanning?query=pr%3A3045+is%3Aopen+path%3Arequirements.txt
> Add filesystem scan in Trivy GHA workflow to scan Python dependencies

- pyproject.toml
Closes #3050 
Check the PR's tests and make sure they are passing. Alternatively, run any of the unit, integration or deployment tests yourself. For example,
```bash
pytest tests/tests_unit/
```
> Pin click to avoid incompatibility issues with Typer

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
Companion PR: https://github.com/nebari-dev/nebari-docker-images/pull/218
Deploy Nebari from this branch, using the JupyterHub and JupyterLab images built by https://github.com/nebari-dev/nebari-docker-images/pull/218. Specify them in the Nebari config file as following:
```yaml
default_images:
jupyterhub: quay.io/nebari/nebari-jupyterhub:upgrade-jupyterhub-5322fbd-20250515
jupyterlab: quay.io/nebari/nebari-jupyterlab:upgrade-jupyterhub-5322fbd-20250515
```
Once Nebari has been deployed, spawn a server and make sure everything works as expected.
Furthermore, you can go to `/hub/admin` and make sure the new version of JupyterHub (5.3.0) has been deployed.
> Upgrade JupyterHub Helm Chart to use 5.3.0

- src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/storage.tf
Fixes https://github.com/nebari-dev/nebari/issues/3139
Tested against our staging deployment, I hit this: https://github.com/nebari-dev/nebari/issues/3137, but it was resolved by deleting the failed helmcharts and re-deploying. 
> override bitnami redis repo (default removed)
